includeWhen: /shouldSubmitForm2441
form:
  topmostSubform[0]:
    Page1[0]:
      f1_1[0]: /primaryFiler/fullName
      f1_2[0]: /primaryFiler/tin
      c1_1[0]: /mfsButEligibleForCdcc
#        c1_2[0]:
      PartI[0]:
        c1_3[0]: /cdccShouldIncludeMoreThanThreeCareProviders
      PartITable[0]:
        BodyRow1[0]:
#          Uses pseudoFact b/c if no care providers, line 1aRow should say 'none'
          f1_3[0]: ~form2441CareProviderNameOrNone
          ColB[0]:
            f1_4[0]: /~careProviders/[0]/pdfAddress
            f1_5[0]:
          f1_6[0]: /~careProviders/[0]/pdfTinEinColumn
          ColD[0]:
            c1_4[0]: /~careProviders/[0]/isHouseholdEmployee
            c1_4[1]: /~careProviders/[0]/isHouseholdEmployeeNo
          f1_7[0]: /~careProviders/[0]/amountPaidForCare
        BodyRow2[0]:
          f1_8[0]: /~careProviders/[1]/displayName
          ColB[0]:
           f1_9[0]: /~careProviders/[1]/pdfAddress
           f1_10[0]:
          f1_11[0]: /~careProviders/[1]/pdfTinEinColumn
          ColD[0]:
            c1_5[0]: /~careProviders/[1]/isHouseholdEmployee
            c1_5[1]: /~careProviders/[1]/isHouseholdEmployeeNo
          f1_12[0]: /~careProviders/[1]/amountPaidForCare
        BodyRow3[0]:
          f1_13[0]: /~careProviders/[2]/displayName
          ColB[0]:
           f1_14[0]: /~careProviders/[2]/pdfAddress
           f1_15[0]:
          f1_16[0]: /~careProviders/[2]/pdfTinEinColumn
          ColD[0]:
            c1_6[0]: /~careProviders/[2]/isHouseholdEmployee
            c1_6[1]: /~careProviders/[2]/isHouseholdEmployeeNo
          f1_17[0]: /~careProviders/[2]/amountPaidForCare
      c1_7[0]: /cdccHasMoreThanThreeQualifyingPersons
      Table_Line2[0]:
        Row1[0]:
          f1_18[0]: /~cdccAllQualifyingPeople/[0]/firstName
          f1_19[0]: /~cdccAllQualifyingPeople/[0]/lastName
          f1_20[0]: /~cdccAllQualifyingPeople/[0]/tin
          c1_8[0]: /~cdccAllQualifyingPeople/[0]/unableToCareForSelfAndOverAge12
          f1_21[0]: /~cdccAllQualifyingPeople/[0]/cdccQualifyingExpenseAmount
        Row2[0]:
          f1_22[0]: /~cdccAllQualifyingPeople/[1]/firstName
          f1_23[0]: /~cdccAllQualifyingPeople/[1]/lastName
          f1_24[0]: /~cdccAllQualifyingPeople/[1]/tin
          c1_9[0]: /~cdccAllQualifyingPeople/[1]/unableToCareForSelfAndOverAge12
          f1_25[0]: /~cdccAllQualifyingPeople/[1]/cdccQualifyingExpenseAmount
        Row3[0]:
          f1_26[0]: /~cdccAllQualifyingPeople/[2]/firstName
          f1_27[0]: /~cdccAllQualifyingPeople/[2]/lastName
          f1_28[0]: /~cdccAllQualifyingPeople/[2]/tin
          c1_10[0]: /~cdccAllQualifyingPeople/[2]/unableToCareForSelfAndOverAge12
          f1_29[0]: /~cdccAllQualifyingPeople/[2]/cdccQualifyingExpenseAmount
      f1_30[0]: /~cdccQualifyingExpenses
      f1_31[0]: /~cdccEarnedIncomePrimaryFilerLine4
      f1_32[0]: /~cdccEarnedIncomeLine5
      f1_33[0]: /~cdccLowerOfEarnedIncomeAndExpenses
      f1_34[0]: /~cdccAgi
      f1_35[0]: /~pdfCdccCareExpensesDecimalAmount
      f1_36[0]: /~cdccTentativeExpenseAmount
      f1_37[0]: /~cdccCreditForPriorYearExpenses
      f1_38[0]: /~cdccTotalEligibleCDCCAmount
      f1_39[0]: /~cdccCreditLimit
      f1_40[0]: /~cdccTotalCredit
    Page2[0]:
      f2_1[0]: /cdccDependentCareBenefitsAmount
      f2_2[0]: /cdccCarryoverAmountFromPriorTaxYear
      f2_3[0]: /cdccForfeitedCredits
      f2_4[0]: /cdccAdjustedDependentCareBenefitsAmount
      Line16_ReadOrder[0]:
        f2_5[0]: /form2441Line16Expenses
      f2_6[0]: /cdccLesserOfAdjustBenefitsAndQualifiedExpenses
      f2_7[0]: /form2441Line18Income
      f2_8[0]: /form2441Line19Income
      f2_9[0]: /cdccTentativeExclusionAmount
      f2_10[0]: /cdccSpecifiedExclusionAmount
      c2_1[0]: /cdccCheckboxSoleProprietorshipNo
      c2_1[1]: /cdccCheckboxSoleProprietorshipYes
      f2_11[0]: /cdccSoleProprietorshipOrPartnershipExclusionAmount
      f2_12[0]: /cdccExclusionAmountNotFromSoleProprietorshipOrPartnership
      f2_13[0]: /cdccDeductibleBenefitsAmount
      f2_14[0]: /cdccExcludedBenefitsAmount
      f2_15[0]: /cdccTaxableBenefits
      f2_16[0]: /~form2441Line27ExpenseCap
      f2_17[0]: /~cdccSumOfDeductibleAndExcludedBenefitsAmount
      f2_18[0]: /~cdccNetAllowableAmount
      f2_19[0]: /~form2441Line30Expenses
      f2_20[0]: /~cdccSmallerOfTotalQualifyingExpensesAmount
otherRequiredFacts:
  - /pdfNone
  - /shouldIncludeCareProviders
  - /hasNoCareProviders
  - /cdccQualified
  - /cdccShouldIncludeMoreThanThreeCareProviders
  - /cdccCareProviders/[0]/displayName
  - /cdccCareProviders/[0]/pdfAddress
  - /cdccCareProviders/[0]/pdfTinEinColumn
  - /cdccCareProviders/[0]/isHouseholdEmployee
  - /cdccCareProviders/[0]/isHouseholdEmployeeNo
  - /cdccCareProviders/[0]/amountPaidForCare
  - /cdccCareProviders/[1]/pdfAddress
  - /cdccCareProviders/[1]/pdfTinEinColumn
  - /cdccCareProviders/[1]/isHouseholdEmployee
  - /cdccCareProviders/[1]/isHouseholdEmployeeNo
  - /cdccCareProviders/[1]/amountPaidForCare
  - /cdccCareProviders/[2]/pdfAddress
  - /cdccCareProviders/[2]/pdfTinEinColumn
  - /cdccCareProviders/[2]/isHouseholdEmployee
  - /cdccCareProviders/[2]/isHouseholdEmployeeNo
  - /cdccCareProviders/[2]/amountPaidForCare
  - /xmlCdccCareExpensesDecimalAmount
  - /cdccQualifyingExpenses
  - /cdccEarnedIncomePrimaryFilerLine4
  - /cdccEarnedIncomeLine5
  - /cdccLowerOfEarnedIncomeAndExpenses
  - /cdccCareExpensesDecimalAmount
  - /cdccTentativeExpenseAmount
  - /cdccCreditForPriorYearExpenses
  - /cdccTotalEligibleCDCCAmount
  - /cdccCreditLimit
  - /cdccTotalCredit
  - /form2441Line27ExpenseCap
  - /cdccSumOfDeductibleAndExcludedBenefitsAmount
  - /cdccNetAllowableAmount
  - /form2441Line30Expenses
  - /cdccSmallerOfTotalQualifyingExpensesAmount
