includeWhen: /wantsCommsFormat
form:
  topmostSubform[0]:
    Page1[0]:
      f1_01[0]: /primaryFiler/fullName
      f1_02[0]: /primaryFiler/tin
#     f1_03[0]:  Form9000 instructions say to leave the address section empty if submitting with your tax return
#     f1_04[0]:  Form9000 instructions say to leave the address section empty if submitting with your tax return
#     f1_05[0]:  Form9000 instructions say to leave the address section empty if submitting with your tax return
#     f1_06[0]:  Form9000 instructions say to leave the address section empty if submitting with your tax return
#     f1_07[0]:  Form9000 instructions say to leave the address section empty if submitting with your tax return
#     f1_08[0]:  Form9000 instructions say to leave the address section empty if submitting with your tax return
      c1_1[0]: ~pdfForm9000StandardPrintIsSelected
      c1_1[1]: ~pdfForm9000LargePrintIsSelected
      c1_1[2]: ~pdfForm9000BrailleIsSelected
      c1_1[3]: ~pdfForm9000AudioIsSelected
      c1_1[4]: ~pdfForm9000PlainTextFileIsSelected
      c1_1[5]: ~pdfForm9000BrailleReadyFileIsSelected
otherRequiredFacts:
  - /commsFormat
