includeWhen: /form8862ClaimingMoreThan4OdcDependents
table:
  rowsCollectionPath: /form8862OdcDependentsCollection
  itemsToSkip: 4
  rowsPerPage: 20
  columns:
    - factExpression: ../fullName
      fieldName: Other dependent name line 13Row
    - factExpression: ../isClaimedDependent
      fieldName: Is your dependent line 16Row
    - factExpression: ../citizenOrUsResidentTest
      fieldName: Is a citizen national or resident of the United States line 17Row
