includeWhen: /qualifiedForSaverCredit
form:
  topmostSubform[0]:
    Page1[0]:
      f1_1[0]: /primaryFiler/fullName space space /pdfSecondaryFiler/fullName
      f1_2[0]: /primaryFiler/tin
      Table_Ln1-6[0]:
        BodyRow1[0]:
          f1_3[0]: /primaryFilerIraAndAbleContributions
          f1_4[0]: /secondaryFilerIraAndAbleContributions
        BodyRow2[0]:
          f1_5[0]: /primaryFilersDeferralsAndContributions
          f1_6[0]: /secondaryFilersDeferralsAndContributions
        BodyRow3[0]:
          f1_7[0]: /primaryFilerTotalContributions
          f1_8[0]: /secondaryFilerTotalContributions
        BodyRow4[0]:
          f1_9[0]: /primaryFilerGrossDistributions
          f1_10[0]: /secondaryFilerGrossDistributions
        BodyRow5[0]:
          f1_11[0]: /submittedPrimaryFilerTotalContributionsLessDistributions
          f1_12[0]: /submittedSecondaryFilerTotalContributionsLessDistributions
        BodyRow6[0]:
          f1_13[0]: /submittedPrimaryFilerMaxCreditCalc
          f1_14[0]: /submittedSecondaryFilerMaxCreditCalc
      f1_15[0]: /combinedCreditLimit
      f1_16[0]: /agi
      f1_17[0]: /pdfSaversCreditMultiplierAsInt
      f1_18[0]: /ratioedCombinedCreditLimit
      f1_19[0]: /limitationBasedOnTaxLiability
      f1_20[0]: /qualifiedSaverCreditAmount
