spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:${MEF_APPS_DB_PORT:32768}/directfile-status
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Batching insert/update/delete
        # https://docs.jboss.org/hibernate/orm/6.4/userguide/html_single/Hibernate_User_Guide.html#batch
        jdbc:
           batch_size: 30  # Hibernate docs recommend a value between 10 and 50
        # Not turning on order_inserts or order_updates since we already generally save as a group
        # Hibernate disables batching for entities having an identity PK, so tax_return_submission won't batch
  liquibase:
    change-log: classpath:db/changelog.yaml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  hikari:
    maximum-pool-size: 50
    max-lifetime: 450000
    minimum-idle: 30
    connection-timeout: 15000

server:
  shutdown: graceful

status:
  # base64-encode the DER-formatted keystore and pass as `keystore-base64`
  keystore-base64: MISSING
  keystore-password: MISSING
  keystore-alias: MISSING
  application-id: ${POD_NAME:dfsys-mef-status-deployment-0}-${DF_AWS_REGION:us-gov-east-1}
  etin: ${STATUS_ETIN:99999}
  asid: 000
  efin: 000
  prod: false
  unit-testing: false
  root-translation-key: status
  translation-key-splitter: .
  ack-poll-in-milliseconds: 60000
  # this field controls whether a Pending Response is returned from the /status endpoint when no submisionId is found.
  # we will want to disable this in the future (likely when SQS communication is enabled).
  status-endpoint-returns-pending-by-default-enabled: true
  status-polling-enabled: true
  messageQueue:
    endpoint: http://localhost:4566
    status-change-queue: status-change-queue
    pending-submission-queue: pending-submission-queue
    dlq-pending-submission-queue: dlq-pending-submission-queue
    region: us-west-2
    accessKey: accessKey
    secretKey: secretKey
    sqs-message-handling-enabled: false
    status-change-publish-enabled: false
  sns:
    endpoint: http://localhost:4566
    status-change-topic-arn: arn:aws:sns:us-west-2:000000000000:status-change-topic
    region: us-west-2
    accessKey: accessKey
    secretKey: secretKey
    status-change-publish-enabled: true
  documentstore:
    region: us-west-2
    accessKey: accessKey
    secretKey: secretKey
    assume-role-arn: assume-role-arn-placeholder
    assume-role-duration-seconds: 1800
    assume-role-session-name: "df-status"
    endpoint: http://localhost:4566/
    bucket: direct-file-taxreturns
    prefix:

aws:
  enabled: false
  default-credentials-provider-chain-enabled: false
  access-key: accessKey
  secret-key: secretKey

direct-file:
  local-encryption:
    local-wrapping-key: ${LOCAL_WRAPPING_KEY:-}

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      discovery:
        enabled: false
      exposure:
        include: health
