spring:
  datasource:
    url: jdbc:postgresql://mef-apps-db:5432/directfile-status

status:
  toolkit: /mef-client-sdk-src
  status-endpoint-returns-pending-by-default-enabled: false
  messageQueue:
    endpoint: http://localstack:4566
    sqs-message-handling-enabled: true
  sns:
    endpoint: http://localstack:4566
  documentstore:
    endpoint: http://localstack:4566/

# these defaults are to match the backend (update/remove once we're fully onto sqs)
direct-file:
  local-encryption:
    local-wrapping-key: ${LOCAL_WRAPPING_KEY}
