status:
  status-endpoint-returns-pending-by-default-enabled: false
  messageQueue:
    sqs-message-handling-enabled: true

direct-file:
  local-encryption:
    local-wrapping-key: ${LOCAL_WRAPPING_KEY}

server:
  port: 8082
