includeWhen: /pdfIncludeSchedule8812
form:
  topmostSubform[0]:
    Page1[0]:
      f1_1[0]: /primaryFiler/fullName space space /pdfSecondaryFiler/fullName
      f1_2[0]: /primaryFiler/tin
      f1_3[0]: /agi
      f1_8[0]: /dependentCreditMagi
      f1_9[0]: /ctcEligibleDependents
      f1_10[0]: /totalPotentialCtc
      f1_11[0]: /odcEligibleDependents
      f1_12[0]: /totalPotentialOdc
      f1_13[0]: /totalPotentialDependentCredits
      f1_14[0]: /dependentCreditPhaseoutThreshold
      f1_15[0]: /roundedDependentCreditMagiAboveThreshold
      f1_16[0]: /dependentCreditPhaseout
      f1_17[0]: /dependentCreditLessPhaseout
      c1_1[0]: /dependentCreditFullyPhasedOut
      c1_1[1]: /dependentCreditNotFullyPhasedOut
      f1_18[0]: /sched8812CreditLimit
      f1_19[0]: /totalCtcAndOdc
    Page2[0]:
      f2_1[0]: /remainingCtcAndOdc
      Line16b_ReadOrder[0]:
        f2_2[0]: /pdf8812Line16bCount
      f2_3[0]: /pdf8812Line16bAmount
      f2_4[0]: /pdf8812Line17
      f2_5[0]: /pdf8812Line18a
      f2_6[0]: /pdf8812Line18b
      c2_2[0]: /pdf8812Line19No
      c2_2[1]: /pdf8812Line19Yes
      f2_7[0]: /pdf8812Line19Amount
      f2_8[0]: /pdf8812Line20
      c2_3[0]: /pdf8812Line20No
      c2_3[1]: /pdf8812Line20Yes
      Line21_ReadOrder[0]:
        f2_9[0]: /pdf8812Line21
      f2_11[0]: /pdf8812Line21
      f2_12[0]: /pdf8812Line24
      f2_13[0]: /pdf8812Line25
      f2_14[0]: /pdf8812Line26
      f2_15[0]: /additionalCtc
