includeWhen: /claimingMoreThan4Dependents
table:
  rowsCollectionPath: /claimedDependentsCollection
  itemsToSkip: 4
  rowsPerPage: 23
  columns:
    - factExpression: ../fullName
      fieldName: NameRow
    - factExpression: ../tin
      fieldName: Social security numberRow
    - factExpression: ../relationship
      fieldName: Relationship to youRow
    - factExpression: ../isClaimedForCTC
      fieldName: Child tax creditRow
    - factExpression: ../isClaimedForODC
      fieldName: Other dependent creditsRow
