includeWhen: /cdccShouldIncludeQualifyingPersonsStatement
table:
  rowsCollectionPath: /~cdccAllQualifyingPeople
  rowsPerPage: 15
  itemsToSkip: 3
  columns:
    - factExpression: ../firstName
      fieldName: a Qualifying persons first nameRow
    - factExpression: ../lastName
      fieldName: b Qualifying persons last nameRow
    - factExpression: ../tin
      fieldName: c Qualifying persons social security numberRow
    - factExpression: ../unableToCareForSelfAndOverAge12
      fieldName: d Check here if the qualifying person was over age 12 and was disabledRow
    - factExpression: ../cdccQualifyingExpenseAmount
      fieldName: e Qualified expenses you incurred and paid in 2024 for the person listed in column aRow
  oncePerPage:
    - factExpression: /primaryFiler/fullName
      fieldName: Taxpayer's name
    - factExpression: /primaryFiler/tin
      fieldName: Taxpayer's TIN
otherRequiredFacts:
  - /cdccQualifyingPeople/*/firstName
  - /cdccQualifyingPeople/*/lastName
  - /cdccQualifyingPeople/*/tin
  - /cdccQualifyingPeople/*/unableToCareForSelfAndOverAge12
  - /cdccQualifyingPeople/*/cdccQualifyingExpenseAmount
  - /cdccQualifyingFilers/*/firstName
  - /cdccQualifyingFilers/*/lastName
  - /cdccQualifyingFilers/*/tin
  - /cdccQualifyingFilers/*/isDisabled
  - /cdccQualifyingFilers/*/cdccQualifyingExpenseAmount
