includeWhen: /requiresSchedule1
form:
  form1040sch1[0]:
    Page1[0]:
      f1_01[0]: /primaryFiler/fullName space space /pdfSecondaryFiler/fullName
      f1_02[0]: /primaryFiler/tin
      # f1_03[0]:
      # f1_04[0]:
      # f1_05[0]:
      # Line2b_ReadOrder[0]:
        # f1_06[0]:
      # f1_07[0]:
      # f1_08[0]:
      # f1_09[0]:
      # f1_10[0]:
      f1_11[0]: /unemploymentCompensation
      # Line8_ReadOrder[0]:
        # f1_12[0]:
      # f1_13[0]:
      # f1_14[0]:
      # f1_15[0]:
      # f1_16[0]:
      # f1_17[0]:
      f1_18[0]: /alaskaPfdIncome
      # f1_19[0]:
      # f1_20[0]:
      # f1_22[0]:
      # f1_22[0]:
      # f1_23[0]:
      # f1_24[0]:
      # f1_25[0]:
      # f1_26[0]:
      # f1_27[0]:
      # f1_28[0]:
      # f1_29[0]:
      # f1_30[0]:
      # f1_31[0]:
      # f1_32[0]:
      # f1_33[0]:
      # Line8z_ReadOrder[0]:
        # f1_34[0]:
        # f1_35[0]:
      # f1_36[0]:
      f1_37[0]: /alaskaPfdIncome
      f1_38[0]: /otherIncome
    Page2[0]:
      f2_01[0]: /educatorExpensesAdjustment
      # f2_02[0]:
      f2_03[0]: /hsaTotalDeductibleAmount
      # f2_04[0]:
      # f2_05[0]:
      # f2_06[0]:
      # f2_07[0]:
      # f2_08[0]:
      # f2_09[0]:
      # f2_10[0]:
      # f2_11[0]:
      # f2_12[0]:
      f2_13[0]: /studentLoanInterestAdjustmentAmount
      # f2_14[0]:
      # f2_15[0]:
      # Line24_ReadOrder[0]:
        # f2_16[0]:
      # f2_17[0]:
      # f2_18[0]:
      # f2_19[0]:
      # f2_20[0]:
      # f2_21[0]:
      # f2_22[0]:
      # f2_23[0]:
      # f2_24[0]:
      # f2_25[0]:
      # f2_26[0]:
      # Line24z_ReadOrder[0]:
        # f2_27[0]:
        # f2_28[0]:
      # f2_29[0]:
      # f2_30[0]:
      f2_31[0]: /adjustmentsToIncome
