includeWhen: /hasSchedule3
form:
  topmostSubform[0]:
    Page1[0]:
      f1_01[0]: /primaryFiler/fullName space space /pdfSecondaryFiler/fullName
      f1_02[0]: /primaryFiler/tin
      # f1_03[0]:
      f1_04[0]: /cdccTotalCredit
      # f1_05[0]:
      f1_06[0]: /qualifiedSaverCreditAmount
      # f1_07[0]:
      # f1_08[0]:
      # Line6a_ReadOrder[0]:
        # f1_09[0]:
      # f1_10[0]:
      # f1_11[0]:
      f1_12[0]: /totalEdc
      # f1_13[0]:
      # f1_14[0]:
      # f1_15[0]:
      # f1_16[0]:
      # f1_17[0]:
      # f1_18[0]:
      # f1_19[0]:
      # f1_20[0]:
      # f1_21[0]:
      # Line6z_ReadOrder[0]:
        # f1_22[0]:
        # f2_23[0]:
      # f1_24[0]:
      f1_25[0]: /totalOtherNonrefundableCredits
      f1_26[0]: /line8OfSchedule3
      f1_27[0]: /netPtcAmountWhenZeroOrPositive
      # f1_28[0]:
      # f1_29[0]:
      # f1_30[0]:
      # Line13_ReadOrder[0]:
        # f1_31[0]:
      # f1_32[0]:
      # f1_33[0]:
      # f1_34[0]:
      # Line13z_ReadOrder[0]:
        # f1_35[0]:
        # f1_36[0]:
      # f1_37[0]:
      # f1_38[0]:
      f1_39[0]: /otherPaymentsAndRefundableCreditsTotal
