includeWhen: /pdfIncludeForm8862
form:
  topmostSubform[0]:
    Page1[0]:
      f1_01[0]: /primaryFiler/fullName space space /pdfSecondaryFiler/fullName
      f1_02[0]: /primaryFiler/tin
      f1_03[0]: /taxYear
      Line2_ReadOrder[0]:
        c1_1[0]: /eitc8862Required
      Checkbox2_ReadOrder[0]:
        c1_2[0]: /ctc8862Required
      # c1_3[0]: AOTCClaimedInd out of scope
      # c1_4[0]: will never be yes if this form is included for ty2023
      c1_4[1]: /eitc8862Required
      c1_5[0]: /pdf8862Line4Yes
      c1_5[1]: /pdf8862Line4No
      f1_04[0]: /scheduleEicDependents/[0]/fullName
      f1_05[0]: /scheduleEicDependents/[1]/fullName
      f1_06[0]: /scheduleEicDependents/[2]/fullName
      c1_6[0]: /form8862RequiredAndHasQualifyingChildren
      c1_6[1]: /form8862RequiredAndHasNoQualifyingChildren
      Hijo1_CombField[0]:
        f1_07[0]: /scheduleEicDependents/[0]/daysLivedWithTPInUS
      Hijo2_CombField[0]:
        f1_08[0]: /scheduleEicDependents/[1]/daysLivedWithTPInUS
      Hijo3_CombField[0]:
        f1_09[0]: /scheduleEicDependents/[2]/daysLivedWithTPInUS
      Hijo1_Birth[0]:
        f1_10[0]: /scheduleEicDependents/[0]/~dobMonth
        f1_11[0]: /scheduleEicDependents/[0]/~dobDay
      Hijo1_Death[0]:
        f1_12[0]: /scheduleEicDependents/[0]/~deathMonth
        f1_13[0]: /scheduleEicDependents/[0]/~deathDay
      Hijo2_Birth[0]:
        f1_14[0]: /scheduleEicDependents/[1]/~dobMonth
        f1_15[0]: /scheduleEicDependents/[1]/~dobDay
      Hijo2_Death[0]:
        f1_16[0]: /scheduleEicDependents/[1]/~deathMonth
        f1_17[0]: /scheduleEicDependents/[1]/~deathDay
      Hijo3_Birth[0]:
        f1_18[0]: /scheduleEicDependents/[2]/~dobMonth
        f1_19[0]: /scheduleEicDependents/[2]/~dobDay
      Hijo3_Death[0]:
        f1_20[0]: /scheduleEicDependents/[2]/~deathMonth
        f1_21[0]: /scheduleEicDependents/[2]/~deathDay
    Page2[0]:
      f2_01[0]: /primaryFiler/daysMainHomeInUS
      f2_02[0]: /pdfSecondaryFiler/daysMainHomeInUS
      f2_03[0]: /primaryFiler/eitc8862Age
      f2_04[0]: /pdfSecondaryFiler/eitc8862Age
      c2_1[0]: /primaryFiler/canBeClaimedNoQc
      c2_1[1]: /primaryFiler/canNotBeClaimedNoQc
      c2_2[0]: /pdfSecondaryFiler/canBeClaimedNoQc
      c2_2[1]: /pdfSecondaryFiler/canNotBeClaimedNoQc
      f2_05[0]: /form8862CtcDependentsCollection/[0]/firstName space /form8862CtcDependentsCollection/[0]/lastNameAndSuffix
      f2_06[0]: /form8862CtcDependentsCollection/[1]/firstName space /form8862CtcDependentsCollection/[1]/lastNameAndSuffix
      f2_07[0]: /form8862CtcDependentsCollection/[2]/firstName space /form8862CtcDependentsCollection/[2]/lastNameAndSuffix
      f2_08[0]: /form8862CtcDependentsCollection/[3]/firstName space /form8862CtcDependentsCollection/[3]/lastNameAndSuffix
      f2_09[0]: /form8862OdcDependentsCollection/[0]/fullName
      f2_10[0]: /form8862OdcDependentsCollection/[1]/fullName
      f2_11[0]: /form8862OdcDependentsCollection/[2]/fullName
      f2_12[0]: /form8862OdcDependentsCollection/[3]/fullName
      c2_3[0]: /form8862CtcDependentsCollection/[0]/residencyTest
      # c2_3[1]: NO should never be checked (ctcDependent must be a qualifying child, which passes residency test)
      c2_4[0]: /form8862CtcDependentsCollection/[1]/residencyTest
      # c2_4[1]: NO should never be checked
      c2_5[0]: /form8862CtcDependentsCollection/[2]/residencyTest
      # c2_5[1]: NO should never be checked
      c2_6[0]: /form8862CtcDependentsCollection/[3]/residencyTest
      # c2_6[1]: NO should never be checked
      c2_7[0]: /form8862CtcDependentsCollection/[0]/eligibleCtc
      # c2_7[1]: NO should never be checked (eligibility is defined in ctcDependentsCollection)
      c2_8[0]: /form8862CtcDependentsCollection/[1]/eligibleCtc
      # c2_8[1]: NO should never be checked
      c2_9[0]: /form8862CtcDependentsCollection/[2]/eligibleCtc
      # c2_9[1]: NO should never be checked
      c2_10[0]: /form8862CtcDependentsCollection/[3]/eligibleCtc
      # c2_10[1]: NO should never be checked
      c2_11[0]: /form8862CtcDependentsCollection/[0]/isClaimedDependent
      # c2_11[1]: NO should never be checked (dependent status is defined through ctcDependentsCollection)
      c2_12[0]: /form8862CtcDependentsCollection/[1]/isClaimedDependent
      # c2_12[1]: NO should never be checked
      c2_13[0]: /form8862CtcDependentsCollection/[2]/isClaimedDependent
      # c2_13[1]: NO should never be checked
      c2_14[0]: /form8862CtcDependentsCollection/[3]/isClaimedDependent
      # c2_14[1]: NO should never be checked
      c2_15[0]: /form8862OdcDependentsCollection/[0]/isClaimedDependent
      # c2_15[1]: NO should never be checked (Dependent status is defined through odcDependentsCollection)
      c2_16[0]: /form8862OdcDependentsCollection/[1]/isClaimedDependent
      # c2_16[1]: NO should never be checked
      c2_17[0]: /form8862OdcDependentsCollection/[2]/isClaimedDependent
      # c2_17[1]: NO should never be checked
      c2_18[0]: /form8862OdcDependentsCollection/[3]/isClaimedDependent
      # c2_18[1]: NO should never be checked
      c2_19[0]: /form8862CtcDependentsCollection/[0]/citizenOrUsResidentTest
      # c2_19[1]: NO should never be checked (included through ctcClaimedDependentsCollection)
      c2_20[0]: /form8862CtcDependentsCollection/[1]/citizenOrUsResidentTest
      # c2_20[1]: NO should never be checked
      c2_21[0]: /form8862CtcDependentsCollection/[2]/citizenOrUsResidentTest
      # c2_21[1]: NO should never be checked
      c2_22[0]: /form8862CtcDependentsCollection/[3]/citizenOrUsResidentTest
      # c2_22[1]: NO should never be checked
      c2_23[0]: /form8862OdcDependentsCollection/[0]/citizenOrUsResidentTest
      # c2_23[1]: NO should never be checked (included through odcDependentsCollection)
      c2_24[0]: /form8862OdcDependentsCollection/[1]/citizenOrUsResidentTest
      # c2_24[1]: NO should never be checked
      c2_25[0]: /form8862OdcDependentsCollection/[2]/citizenOrUsResidentTest
      # c2_25[1]: NO should never be checked
      c2_26[0]: /form8862OdcDependentsCollection/[3]/citizenOrUsResidentTest
      # c2_26[1]: NO should never be checked
    # Page3[0]:
      # f3_01[0]: out of scope start v
      # f3_02[0]:
      # f3_03[0]:
      # c3_1[0]:
      # c3_1[1]:
      # c3_2[0]:
      # c3_2[1]:
      # c3_3[0]:
      # c3_3[1]:
      # c3_4[0]:
      # c3_4[1]:
      # c3_5[0]:
      # c3_5[1]:
      # c3_6[0]:
      # c3_6[1]: out of scope end ^
otherRequiredFacts:
  - /form8862RequiredAndHasQualifyingChildren
  - /scheduleEicDependents/[0]/birthDateIfBornInTaxYear
  - /scheduleEicDependents/[1]/birthDateIfBornInTaxYear
  - /scheduleEicDependents/[2]/birthDateIfBornInTaxYear
  - /scheduleEicDependents/[0]/deathDateIfDiedInTaxYear
  - /scheduleEicDependents/[1]/deathDateIfDiedInTaxYear
  - /scheduleEicDependents/[2]/deathDateIfDiedInTaxYear
