includeWhen: /wantsCustomLanguage
form:
  topmostSubform[0]:
    Page1[0]:
      f1_1[0]: /primaryFiler/fullName
      f1_2[0]: /primaryFiler/tin
      Line1_ReadOrder[0]:
        c1_1[0]: ~englishIsSelectedLep
        c1_1[1]: ~spanishIsSelectedLep
        Coreano[0]:
          c1_1[0]: ~koreanIsSelectedLep
        Vietnamita[0]:
          c1_1[0]: ~vietnameseIsSelectedLep
        Russo[0]:
          c1_1[0]: ~russianIsSelectedLep
        Arabe[0]:
          c1_1[0]: ~arabicIsSelectedLep
        CriolloHaitiano[0]:
          c1_1[0]: ~haitianIsSelectedLep
        Tagalo[0]:
          c1_1[0]: ~tagalogIsSelectedLep
        Portugues[0]:
          c1_1[0]: ~portugueseIsSelectedLep
        Polaco[0]:
          c1_1[0]: ~polishIsSelectedLep
        Farsi[0]:
          c1_1[0]: ~farsiIsSelectedLep
      Frances[0]:
        c1_1[0]: ~frenchIsSelectedLep
      Japones[0]:
        c1_1[0]: ~japaneseIsSelectedLep
      Gujarati[0]:
        c1_1[0]: ~gujaratiIsSelectedLep
      Punjabi[0]:
        c1_1[0]: ~punjabiIsSelectedLep
      Camboyano[0]:
        c1_1[0]: ~khmerIsSelectedLep
      Urdu[0]:
        c1_1[0]: ~urduIsSelectedLep
      Bengali[0]:
        c1_1[0]: ~bengaliIsSelectedLep
      c1_1[0]: ~italianIsSelectedLep
      ChinoTradicional[0]:
        c1_1[0]: ~chineseTraditionalIsSelectedLep
      ChinoSimplificado[0]:
        c1_1[0]: ~chineseSimplifiedIsSelectedLep
otherRequiredFacts:
  - /languagePreference
