includeWhen: /xmlOver65SRIndicator
form:
  topmostSubform[0]:
    Page1[0]:
      # f1_01[0]:
      # f1_02[0]:
      # f1_03[0]:
      f1_04[0]: /primaryFiler/firstNameAndInitial
      f1_05[0]: /primaryFiler/lastName
      f1_06[0]: /primaryFiler/tin
      f1_07[0]: /pdfSecondaryFiler/firstNameAndInitial
      f1_08[0]: /pdfSecondaryFiler/lastName
      f1_09[0]: /pdfSpouseTin
      Direccion_ReadOrder[0]:
        f1_10[0]: /address/streetAddress space /address/streetAddressLine2
        # f1_11[0]:
        f1_12[0]: /address/city
        f1_13[0]: /address/stateOrProvence
        f1_14[0]: /address/postalCode
        # f1_15[0]:
        # f1_16[0]:
        # f1_17[0]:
      c1_01[0]: /primaryFiler/potusElection
      c1_02[0]: /pdfSecondaryFiler/potusElection
      c1_03[0]: /isFilingStatusSingle
      c1_03[1]: /isFilingStatusMFJ
      c1_03[2]: /isFilingStatusMFS
      c1_03[3]: /isFilingStatusHOH
      c1_03[4]: /isFilingStatusQSS
      f1_18[0]: /mfsSpouseOrQSSAndHOHNotDependentChild space space /xmlNraLiteralCd
      # c1_04[0]: Off
      # f1_19[0]:
      # c1_05[0]: Off
      c1_05[1]: /notDigitalAssets
      c1_06[0]: /primarySomeoneCanClaimForTaxBenefits
      c1_07[0]: /secondarySomeoneCanClaimForTaxBenefits
      # c1_08[0]: Off
      c1_09[0]: /primaryFiler/age65OrOlder
      c1_10[0]: /primaryFiler/isBlind
      c1_11[0]: /isSpouse65OrOlder
      c1_12[0]: /secondaryFilerIsBlindIndicatorXml
      Dependientes_ReadOrder[0]:
        c1_13[0]: /claimingMoreThan4Dependents
      Table_Dependientes[0]:
        BodyRow1[0]:
          f1_20[0]: /claimedDependentsCollection/[0]/fullName
          f1_21[0]: /claimedDependentsCollection/[0]/tin
          f1_22[0]: /claimedDependentsCollection/[0]/relationship
          c1_14[0]: /claimedDependentsCollection/[0]/isClaimedForCTC
          c1_15[0]: /claimedDependentsCollection/[0]/isClaimedForODC
        BodyRow2[0]:
          f1_23[0]: /claimedDependentsCollection/[1]/fullName
          f1_24[0]: /claimedDependentsCollection/[1]/tin
          f1_25[0]: /claimedDependentsCollection/[1]/relationship
          c1_16[0]: /claimedDependentsCollection/[1]/isClaimedForCTC
          c1_17[0]: /claimedDependentsCollection/[1]/isClaimedForODC
        BodyRow3[0]:
          f1_26[0]: /claimedDependentsCollection/[2]/fullName
          f1_27[0]: /claimedDependentsCollection/[2]/tin
          f1_28[0]: /claimedDependentsCollection/[2]/relationship
          c1_18[0]: /claimedDependentsCollection/[2]/isClaimedForCTC
          c1_19[0]: /claimedDependentsCollection/[2]/isClaimedForODC
        BodyRow4[0]:
          f1_29[0]: /claimedDependentsCollection/[3]/fullName
          f1_30[0]: /claimedDependentsCollection/[3]/tin
          f1_31[0]: /claimedDependentsCollection/[3]/relationship
          c1_20[0]: /claimedDependentsCollection/[3]/isClaimedForCTC
          c1_21[0]: /claimedDependentsCollection/[3]/isClaimedForODC
      f1_32[0]: /wages
      f1_33[0]: /unreportedHouseholdWages
      f1_34[0]: /unreportedTipIncome
      f1_35[0]: /medicareWaiverPayments
      f1_36[0]: /taxableDependentCare
      f1_37[0]: /employerProvidedAdoptionBenefits
      f1_38[0]: /wagesFrom8919
      f1_39[0]: /otherEarnedIncome
      f1_40[0]: /combatPayAmount
      f1_41[0]: /employerIncomeSubtotal
    Page2[0]:
      f2_01[0]: /taxExemptInterest
      f2_02[0]: /interestIncome
      f2_03[0]: /qualifiedDividends
      f2_04[0]: /ordinaryDividends
      f2_05[0]: /iraDistributions
      f2_06[0]: /taxableIraDistributions
      f2_07[0]: /pensionsAndAnnuities
      f2_08[0]: /taxablePensionsAndAnnuitiesDisplay
      f2_09[0]: ~positiveSocialSecurityBenefitsOrEmpty
      f2_10[0]: /taxableSocialSecurityBenefits
      c2_01[0]: /socialSecurityLumpSum
      Line7_ReadOrder[0]:
        c2_02[0]: /capitalGainsScheduleDNotRequired
      f2_11[0]: /capitalGainsOrLosses
      f2_12[0]: /otherIncome
      f2_13[0]: /totalIncome
      f2_14[0]: /adjustmentsToIncome
      f2_15[0]: /agi
      f2_16[0]: /standardOrItemizedDeductions
      f2_17[0]: /qualifiedBusinessIncomeDeduction
      f2_18[0]: /totalDeductions
      f2_19[0]: /taxableIncome
      Line16_ReadOrder[0]:
        c2_03[0]: /form8814Included
        c2_04[0]: /form4972Included
        c2_05[0]: /formOtherIncluded
        f2_20[0]: /otherFormName
      f2_21[0]: /tentativeTaxFromTaxableIncome
      f2_22[0]: /totalAdditionalTaxesOwed
      f2_23[0]: /totalTentativeTax
      f2_24[0]: /totalCtcAndOdc
      f2_25[0]: /line8OfSchedule3
      f2_26[0]: /nonRefundableCredits
      f2_27[0]: /taxLessNonRefundableCredits
      f2_28[0]: /line21OfSchedule2
      f2_29[0]: /totalTax
      f2_30[0]: /formW2Withholding
      f2_31[0]: /form1099Withholding
      f2_32[0]: /otherFormWithholding
      f2_33[0]: /totalWithholding
      f2_34[0]: /estimatedAndFromLastYear
    Page3[0]:
      f3_01[0]: /earnedIncomeCredit
      f3_02[0]: /additionalCtc
      f3_03[0]: /americanOpportunityCredit
      f3_05[0]: /otherPaymentsAndRefundableCreditsTotal
      f3_06[0]: /totalOtherPaymentsRefundableCredits
      f3_07[0]: /totalPayments
      f3_08[0]: /overpayment
      Line35a_ReadOrder[0]:
        c3_01[0]: /form8888Attached
      f3_09[0]: /overpayment
      RoutingNo[0]:
        f3_10[0]: ~pdfRoutingNumberOrXs
      c3_02[0]: /refundAccountIsChecking
      c3_02[1]: /refundAccountIsSavings
      AccountNo[0]:
        f3_11[0]: ~pdfAccountNumberOrXs
      f3_12[0]: /appliedToNextYearEstimated
      f3_13[0]: /balanceDue
      c3_03[0]: /wantsThirdPartyDesignee
      c3_03[1]: /wantsThirdPartyDesigneeNo
      f3_15[0]: /pdfThirdPartyDesigneeFullName
      f3_16[0]: /pdfThirdPartyDesigneePhone
      f3_17[0]: /pdfThirdPartyDesigneePin
      f3_18[0]: /primaryFiler/occupation
      f3_19[0]: /primaryFiler/identityPin
      f3_20[0]: /pdfSecondaryFiler/occupation
      f3_21[0]: /pdfSecondaryFiler/identityPin
      f3_22[0]: /phone
      f3_23[0]: /email
      # f3_24[0]:
      # f3_25[0]:
      # c3_04[0]: Off
      # f3_26[0]:
      # f3_27[0]:
      # f3_28[0]:
      # f3_29[0]:
    # we remove page 4
    # Page4[0]:
      # f4_01[0]:
otherRequiredFacts:
  - /dueRefund
  - /xmlRefundBankAccount
  - /socialSecurityBenefits
