includeForEach: /formW2s
form:
  topmostSubform[0]:
    CopyB[0]:
      BoxA_ReadOrder[0]:
        f2_01[0]: /formW2s/*/usedTin
      Col_Left[0]:
        f2_02[0]: /formW2s/*/ein
        f2_03[0]: /formW2s/*/employerName newLine /formW2s/*/writableEmployerNameLine2 newLine /formW2s/*/employerAddress
#       f2_04[0]:
        FirstName_ReadOrder[0]:
          f2_05[0]: /formW2s/*/filer/firstNameAndInitial
        LastName_ReadOrder[0]:
          f2_06[0]: /formW2s/*/filer/lastName
        f2_07[0]: /formW2s/*/suffix
        f2_08[0]: /formW2s/*/address
      Col_Right[0]:
        Box1_ReadOrder[0]:
          f2_09[0]: /formW2s/*/wages
        f2_10[0]: /formW2s/*/federalWithholding
        Box3_ReadOrder[0]:
          f2_11[0]: /formW2s/*/oasdiWages
        f2_12[0]: /formW2s/*/oasdiWithholding
        Box5_ReadOrder[0]:
          f2_13[0]: /formW2s/*/medicareWages
        f2_14[0]: /formW2s/*/medicareWithholding
        Box7_ReadOrder[0]:
          f2_15[0]: /formW2s/*/oasdiTips
        f2_16[0]: /formW2s/*/allocatedTips
#       Box9_ReadOrder[0]:
#         f2_17[0]:
        f2_18[0]: /formW2s/*/dependentCareBenefits
        Box11__ReadOrder[0]:
          f2_19[0]: /formW2s/*/nonQualifiedPlans
        Box12_ReadOrder[0]:
          f2_20[0]: /formW2s/*/~box12Code1
          f2_21[0]: /formW2s/*/~box12Amount1
          f2_22[0]: /formW2s/*/~box12Code2
          f2_23[0]: /formW2s/*/~box12Amount2
          f2_24[0]: /formW2s/*/~box12Code3
          f2_25[0]: /formW2s/*/~box12Amount3
          f2_26[0]: /formW2s/*/~box12Code4
          f2_27[0]: /formW2s/*/~box12Amount4
        Statutory_ReadOrder[0]:
          c2_2[0]: /formW2s/*/statutoryEmployee
        Retirement_ReadOrder[0]:
          c2_3[0]: /formW2s/*/retirementPlan
        c2_4[0]: /formW2s/*/thirdPartySickPay
        f2_28[0]: /formW2s/*/~box14Text
      Boxes15_ReadOrder[0]:
        Box15_ReadOrder[0]:
          f2_29[0]: /formW2s/*/pdfStateCode
        f2_30[0]: /formW2s/*/stateEmployerId
#       f2_31[0]:
#       f2_32[0]:
      Box16_ReadOrder[0]:
        f2_33[0]: /formW2s/*/stateWages
#       f2_34[0]:
      Box17_ReadOrder[0]:
        f2_35[0]: /formW2s/*/stateWithholding
#       f2_36[0]:
      Box18_ReadOrder[0]:
        f2_37[0]: /formW2s/*/localWages
#       f2_38[0]:
      Box19_ReadOrder[0]:
        f2_39[0]: /formW2s/*/localWithholding
#       f2_40[0]:
      f2_41[0]: /formW2s/*/locality
#     f2_42[0]:
otherRequiredFacts:
  - /formW2s/*/uncollectedOasdiTaxOnTips
  - /formW2s/*/uncollectedMedicareTaxOnTips
  - /formW2s/*/taxableLifeInsuranceOver50k
  - /formW2s/*/401kDeferrals
  - /formW2s/*/403bDeferrals
  - /formW2s/*/sarsepDeferrals
  - /formW2s/*/457bDeferrals
  - /formW2s/*/501c18Deferrals
  - /formW2s/*/nontaxableSickPay
  - /formW2s/*/goldenParachuteExciseTax
  - /formW2s/*/expenseReimbursements
  - /formW2s/*/uncollectedOasdiTaxOnLifeInsuranceOver50k
  - /formW2s/*/uncollectedMedicareTaxOnLifeInsuranceOver50k
  - /formW2s/*/armedForcesMovingExpenses
  - /formW2s/*/writableCombatPay
  - /formW2s/*/archerMsaContributions
  - /formW2s/*/simpleContributions
  - /formW2s/*/adoptionBenefits
  - /formW2s/*/nsoIncome
  - /formW2s/*/employerHsaContributions
  - /formW2s/*/409aDeferrals
  - /formW2s/*/nqdcDeferrals
  - /formW2s/*/roth401kContributions
  - /formW2s/*/roth403bContributions
  - /formW2s/*/healthCoverageCost
  - /formW2s/*/roth457bContributions
  - /formW2s/*/qsehraBenefits
  - /formW2s/*/83iIncome
  - /formW2s/*/83iDeferrals
  - /formW2s/*/nonTaxableMedicaidWaiverPayments
  - /formW2s/*/414_H
  - /formW2s/*/414_H_CU
  - /formW2s/*/414H
  - /formW2s/*/414HCU
  - /formW2s/*/414HSUB
  - /formW2s/*/ADDITIONAL_MEDICARE_TAX
  - /formW2s/*/ERS
  - /formW2s/*/ERSNYSRE
  - /formW2s/*/ERSRETCO
  - /formW2s/*/BOX14_NJ_FLI
  - /formW2s/*/IRC125S
  - /formW2s/*/MEDICARE_TAX
  - /formW2s/*/NYRET
  - /formW2s/*/NYSERS
  - /formW2s/*/NYSRETCO
  - /formW2s/*/PUBRET
  - /formW2s/*/RET
  - /formW2s/*/RETDEF
  - /formW2s/*/RETMT
  - /formW2s/*/RETSH
  - /formW2s/*/RETSM
  - /formW2s/*/RETSUM
  - /formW2s/*/RRTA_COMPENSATION
  - /formW2s/*/BOX14_MD_STPICKUP
  - /formW2s/*/TIER_1_TAX
  - /formW2s/*/TIER_2_TAX
  - /formW2s/*/TIER3RET
  - /formW2s/*/TIER4
  - /formW2s/*/TIER4RET
  - /formW2s/*/BOX14_NJ_UIHCWD
  - /formW2s/*/BOX14_NJ_UIWFSWF
customMaps:
  box12:
    /formW2s/*/uncollectedOasdiTaxOnTips: A
    /formW2s/*/uncollectedMedicareTaxOnTips: B
    /formW2s/*/taxableLifeInsuranceOver50k: C
    /formW2s/*/401kDeferrals: D
    /formW2s/*/403bDeferrals: E
    /formW2s/*/sarsepDeferrals: F
    /formW2s/*/457bDeferrals: G
    /formW2s/*/501c18Deferrals: H
    /formW2s/*/nontaxableSickPay: J
    /formW2s/*/goldenParachuteExciseTax: K
    /formW2s/*/expenseReimbursements: L
    /formW2s/*/uncollectedOasdiTaxOnLifeInsuranceOver50k: M
    /formW2s/*/uncollectedMedicareTaxOnLifeInsuranceOver50k: N
    /formW2s/*/armedForcesMovingExpenses: P
    /formW2s/*/writableCombatPay: Q
    /formW2s/*/archerMsaContributions: R
    /formW2s/*/simpleContributions: S
    /formW2s/*/adoptionBenefits: T
    /formW2s/*/nsoIncome: V
    /formW2s/*/employerHsaContributions: W
    /formW2s/*/409aDeferrals: Y
    /formW2s/*/nqdcDeferrals: Z
    /formW2s/*/roth401kContributions: AA
    /formW2s/*/roth403bContributions: BB
    /formW2s/*/healthCoverageCost: DD
    /formW2s/*/roth457bContributions: EE
    /formW2s/*/qsehraBenefits: FF
    /formW2s/*/83iIncome: GG
    /formW2s/*/83iDeferrals: HH
    /formW2s/*/nonTaxableMedicaidWaiverPayments: II
  box14:
    /formW2s/*/414_H: 414 (H)
    /formW2s/*/414_H_CU: 414 (H) (CU)
    /formW2s/*/414H: 414H
    /formW2s/*/414HCU: 414HCU
    /formW2s/*/414HSUB: 414HSUB
    /formW2s/*/ADDITIONAL_MEDICARE_TAX: Additional Medicare Tax
    /formW2s/*/ERS: ERS
    /formW2s/*/ERSNYSRE: ERSNYSRE
    /formW2s/*/ERSRETCO: ERSRETCO
    /formW2s/*/BOX14_NJ_FLI: FLI
    /formW2s/*/IRC125S: IRC125S
    /formW2s/*/MEDICARE_TAX: Medicare Tax
    /formW2s/*/NYRET: NYRET
    /formW2s/*/NYSERS: NYSERS
    /formW2s/*/NYSRETCO: NYSRETCO
    /formW2s/*/PUBRET: PUBRET
    /formW2s/*/RET: RET
    /formW2s/*/RETDEF: RETDEF
    /formW2s/*/RETMT: RETMT
    /formW2s/*/RETSH: RETSH
    /formW2s/*/RETSM: RETSM
    /formW2s/*/RETSUM: RETSUM
    /formW2s/*/RRTA_COMPENSATION: RRTA Compensation
    /formW2s/*/BOX14_MD_STPICKUP: STPICKUP
    /formW2s/*/TIER_1_TAX: Tier 1 Tax
    /formW2s/*/TIER_2_TAX: Tier 2 Tax
    /formW2s/*/TIER3RET: TIER3RET
    /formW2s/*/TIER4: TIER4
    /formW2s/*/TIER4RET: TIER4RET
    /formW2s/*/BOX14_NJ_UIHCWD: UI HC WD
    /formW2s/*/BOX14_NJ_UIWFSWF: UI WF SWF
