includeWhen: /claimingMoreThan4Dependents
table:
  rowsCollectionPath: /claimedDependentsCollection
  itemsToSkip: 4
  rowsPerPage: 23
  columns:
    - factExpression: ../fullName
      fieldName: NombreRow
    - factExpression: ../tin
      fieldName: Número de Seguro SocialRow
    - factExpression: ../relationship
      fieldName: Parentesco con ustedRow
    - factExpression: ../isClaimedForCTC
      fieldName: Crédito tributario por hijosRow
    - factExpression: ../isClaimedForODC
      fieldName: Crédito por otros dependientesRow
