receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  debug:
    verbosity: detailed # normal

processors:
  batch:
  transform:
    metric_statements:
      - context: datapoint
        statements:
        - set(attributes["application"], resource.attributes["service.name"])
extensions:
  health_check:
  zpages:

service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [batch, transform]
      exporters: [debug, prometheus]
  
  # Configuration for otel-exporter itself
  telemetry:
    logs:
      level: DEBUG
    metrics:
      level: detailed
