global:
  scrape_interval: 3s

scrape_configs:
- job_name: "prometheus"
  static_configs:
  - targets:
    - host.docker.internal:9090

# Direct file targets
- job_name: "otel-collector"
  static_configs:
    - targets: ["otel-collector:8888"] # otel-collector metricts
    - targets: ["otel-collector:8889"] # exported app metrics
- job_name: "csp-simulator"
  static_configs:
  - targets:
    - csp-simulator:8080

# Local targets
- job_name: "node"
  # Export local stats with node_exporter
  static_configs:
  - targets:
    - host.docker.internal:9100
