includeWhen: /requiresSchedule2
form:
  form1[0]:
    Page1[0]:
      f1_01[0]: /primaryFiler/fullName space space /pdfSecondaryFiler/fullName
      f1_02[0]: /primaryFiler/tin
      Line1a_ReadOrder[0]:
        f1_03[0]: /lesserOfNetPtcAmountAndRepaymentLimitation
      # f1_04[0]:
      # f1_05[0]:
      # f1_06[0]:
      # Line1e_ReadOrder[0]:
        # c1_1[0]: Off
        # c1_1[1]: Off
        # c1_1[2]: Off
        # c1_1[3]: Off
      # f1_07[0]:
      # Line1f_ReadOrder[0]:
        # c1_2[0]: Off
        # c1_2[1]: Off
        # c1_2[2]: Off
        # c1_2[3]: Off
      # f1_08[0]:
      # f1_09[0]:
      # f1_10[0]:
      f1_11[0]: /totalAdditionalTaxesOwed
      # f1_12[0]:
      f1_13[0]: /totalAdditionalTaxesOwed
      # f1_14[0]:
      # Line5_ReadOrder[0]:
        # f1_15[0]:
      # f1_16[0]:
      # f1_17[0]:
      # Line8_ReadOrder[0]:
        # c1_3[0]: Off
      # f1_18[0]:
      # f1_19[0]:
      # f1_20[0]:
      # f1_21[0]:
      # f1_22[0]:
      # f1_23[0]:
      # f1_24[0]:
      # f1_25[0]:
      # f1_26[0]:
    # Page2[0]:
      # Line17a_ReadOrder[0]:
        # Line17_ReadOrder[0]:
          # f2_01[0]:
        # f2_02[0]:
      # f2_03[0]:
      # f2_04[0]:
      # f2_05[0]:
      # f2_06[0]:
      # f2_07[0]:
      # f2_08[0]:
      # f2_09[0]:
      # f2_10[0]:
      # f2_11[0]:
      # f2_12[0]:
      # f2_13[0]:
      # f2_14[0]:
      # f2_15[0]:
      # f2_16[0]:
      # f2_17[0]:
      # f2_18[0]:
      # Line17z_ReadOrder[0]:
        # f2_19[0]:
        # f2_20[0]:
      # f2_21[0]:
      # f2_22[0]:
      # f2_23[0]:
      # Line20_ReadOrder[0]:
        # f2_24[0]:
      # f2_25[0]:
