includeWhen: /needsToFileForm8962
form:
  topmostSubform[0]:
    Page1[0]:
      f1_1[0]: /primaryFiler/fullName space space /pdfSecondaryFiler/fullName
      f1_2[0]: /primaryFiler/tin
      c1_1[0]: /claimingMfsException
      f1_3[0]: /taxFamilySize
      f1_4[0]: /ptcMagi
      # f1_5[0]:
      f1_6[0]: /householdIncome
      c1_2[0]: /federalPovertyLineLocationIsAlaska
      c1_2[1]: /federalPovertyLineLocationIsHawaii
      c1_2[2]: /federalPovertyLineLocationIsOther
      f1_7[0]: /federalPovertyLevelThreshold
      f1_8[0]: /householdIncomeAsPercent
      f1_9[0]: /formattedApplicableFigure
      f1_10[0]: /ptcAnnualContributionAmount
      f1_11[0]: /ptcMontlyContributionAmount
      # c1_4[0]: Off
      c1_4[1]: /flowTrue
      c1_5[0]: /ptcCanReportAnnualTotals
      c1_5[1]: /needsToFileForm8962Monthly
      Part2Table1[0]:
        BodyRow1[0]:
          f1_13[0]: /totalPtcAnnualPremium
          f1_14[0]: /totalAnnualSlcspPremium
          f1_15[0]: /submittedAnnualContributionAmountForAnnual
          f1_16[0]: /annualMaxPremiumAssitance
          f1_17[0]: /annualPtcAllowed
          f1_18[0]: /totalAnnualAptcAmount
      Part2Table2[0]:
        BodyRow1[0]:
          f1_19[0]: /monthlyPtcPremiumForJan
          f1_20[0]: /monthlyPtcSlcspPremiumForJan
          f1_21[0]: /monthlyPtcContributionAmountForJan
          f1_22[0]: /monthlyPtcMaxPremiumAssitanceForJan
          f1_23[0]: /monthlyPtcAllowedForJan
          f1_24[0]: /monthlyAptcPremiumForJan
        BodyRow2[0]:
          f1_25[0]: /monthlyPtcPremiumForFeb
          f1_26[0]: /monthlyPtcSlcspPremiumForFeb
          f1_27[0]: /monthlyPtcContributionAmountForFeb
          f1_28[0]: /monthlyPtcMaxPremiumAssitanceForFeb
          f1_29[0]: /monthlyPtcAllowedForFeb
          f1_30[0]: /monthlyAptcPremiumForFeb
        BodyRow3[0]:
          f1_31[0]: /monthlyPtcPremiumForMar
          f1_32[0]: /monthlyPtcSlcspPremiumForMar
          f1_33[0]: /monthlyPtcContributionAmountForMar
          f1_34[0]: /monthlyPtcMaxPremiumAssitanceForMar
          f1_35[0]: /monthlyPtcAllowedForMar
          f1_36[0]: /monthlyAptcPremiumForMar
        BodyRow4[0]:
          f1_37[0]: /monthlyPtcPremiumForApr
          f1_38[0]: /monthlyPtcSlcspPremiumForApr
          f1_39[0]: /monthlyPtcContributionAmountForApr
          f1_40[0]: /monthlyPtcMaxPremiumAssitanceForApr
          f1_41[0]: /monthlyPtcAllowedForApr
          f1_42[0]: /monthlyAptcPremiumForApr
        BodyRow5[0]:
          f1_43[0]: /monthlyPtcPremiumForMay
          f1_44[0]: /monthlyPtcSlcspPremiumForMay
          f1_45[0]: /monthlyPtcContributionAmountForMay
          f1_46[0]: /monthlyPtcMaxPremiumAssitanceForMay
          f1_47[0]: /monthlyPtcAllowedForMay
          f1_48[0]: /monthlyAptcPremiumForMay
        BodyRow6[0]:
          f1_49[0]: /monthlyPtcPremiumForJun
          f1_50[0]: /monthlyPtcSlcspPremiumForJun
          f1_51[0]: /monthlyPtcContributionAmountForJun
          f1_52[0]: /monthlyPtcMaxPremiumAssitanceForJun
          f1_53[0]: /monthlyPtcAllowedForJun
          f1_54[0]: /monthlyAptcPremiumForJun
        BodyRow7[0]:
          f1_55[0]: /monthlyPtcPremiumForJul
          f1_56[0]: /monthlyPtcSlcspPremiumForJul
          f1_57[0]: /monthlyPtcContributionAmountForJul
          f1_58[0]: /monthlyPtcMaxPremiumAssitanceForJul
          f1_59[0]: /monthlyPtcAllowedForJul
          f1_60[0]: /monthlyAptcPremiumForJul
        BodyRow8[0]:
          f1_61[0]: /monthlyPtcPremiumForAug
          f1_62[0]: /monthlyPtcSlcspPremiumForAug
          f1_63[0]: /monthlyPtcContributionAmountForAug
          f1_64[0]: /monthlyPtcMaxPremiumAssitanceForAug
          f1_65[0]: /monthlyPtcAllowedForAug
          f1_66[0]: /monthlyAptcPremiumForAug
        BodyRow9[0]:
          f1_67[0]: /monthlyPtcPremiumForSep
          f1_68[0]: /monthlyPtcSlcspPremiumForSep
          f1_69[0]: /monthlyPtcContributionAmountForSep
          f1_70[0]: /monthlyPtcMaxPremiumAssitanceForSep
          f1_71[0]: /monthlyPtcAllowedForSep
          f1_72[0]: /monthlyAptcPremiumForSep
        BodyRow10[0]:
          f1_73[0]: /monthlyPtcPremiumForOct
          f1_74[0]: /monthlyPtcSlcspPremiumForOct
          f1_75[0]: /monthlyPtcContributionAmountForOct
          f1_76[0]: /monthlyPtcMaxPremiumAssitanceForOct
          f1_77[0]: /monthlyPtcAllowedForOct
          f1_78[0]: /monthlyAptcPremiumForOct
        BodyRow11[0]:
          f1_79[0]: /monthlyPtcPremiumForNov
          f1_80[0]: /monthlyPtcSlcspPremiumForNov
          f1_81[0]: /monthlyPtcContributionAmountForNov
          f1_82[0]: /monthlyPtcMaxPremiumAssitanceForNov
          f1_83[0]: /monthlyPtcAllowedForNov
          f1_84[0]: /monthlyAptcPremiumForNov
        BodyRow12[0]:
          f1_85[0]: /monthlyPtcPremiumForDec
          f1_86[0]: /monthlyPtcSlcspPremiumForDec
          f1_87[0]: /monthlyPtcContributionAmountForDec
          f1_88[0]: /monthlyPtcMaxPremiumAssitanceForDec
          f1_89[0]: /monthlyPtcAllowedForDec
          f1_90[0]: /monthlyAptcPremiumForDec
      f1_91[0]: /totalPtcAmountAllowed
      f1_92[0]: /totalAptcAmountTaken
      f1_93[0]: /netPtcAmountWhenZeroOrPositive
      f1_94[0]: /netPtcAmountWhenNegative
      f1_95[0]: /ptcRepaymentLimitation
      f1_96[0]: /lesserOfNetPtcAmountAndRepaymentLimitation
    Page2[0]:
      # f2_1[0]:
      # f2_2[0]:
      # f2_3[0]:
      # f2_4[0]:
      Lines30e-g[0]:
        # f2_5[0]:
        # f2_6[0]:
        # f2_7[0]:
      # f2_8[0]:
      # f2_9[0]:
      # f2_10[0]:
      # f2_11[0]:
      Lines31e-g[0]:
        # f2_12[0]:
        # f2_13[0]:
        # f2_14[0]:
      # f2_15[0]:
      # f2_16[0]:
      # f2_17[0]:
      # f2_18[0]:
      Lines32e-g[0]:
        # f2_19[0]:
        # f2_20[0]:
        # f2_21[0]:
      # f2_22[0]:
      # f2_23[0]:
      # f2_24[0]:
      # f2_25[0]:
      Lines33e-g[0]:
        # f2_26[0]:
        # f2_27[0]:
        # f2_28[0]:
      c2_1[0]: Off
      c2_1[1]: Off
      # f2_29[0]:
      # f2_30[0]:
      # f2_31[0]:
      # f2_32[0]:
      # f2_33[0]:
      # f2_34[0]:
      # f2_35[0]:
      # f2_36[0]:
