includeWhen: /isReceivingEdc
form:
  topmostSubform[0]:
    Page1[0]:
      f1_1[0]: /primaryFiler/fullName space space /pdfSecondaryFiler/fullName
      f1_2[0]: /primaryFiler/tin
      c1_1[0]: /edcLine1
      c1_1[1]: /edcLine2
      Married[0]:
        c1_1[0]: /edcLine3
        c1_1[1]: /edcLine4
        c1_1[2]: /edcLine5
        c1_1[3]: /edcLine6
        c1_1[4]: /edcLine7
      MarriedSeparate[0]:
        c1_1[0]: /edcLine8
        c1_1[1]: /edcLine9
      c1_2[0]: /allDisabledEdcQualifiedDontNeedPhysicianStatement
    Page2[0]:
      f2_1[0]: /edcFilingStatusAmt
      f2_2[0]: /statusBasedDisabilityIncome
      f2_3[0]: /lesserOfFilingStatusAmountAndTaxableDisabilityIncome
      f2_4[0]: /edcNonTaxableSocialSecurityAndRailroadBenefits
      f2_5[0]: /edcNonTaxableIncomeNotIncludingSocialSecurityAndRrb
      f2_6[0]: /edcTotalNonTaxableAmount
      f2_7[0]: /agi
      f2_8[0]: /edcExemptionAmount
      f2_9[0]: /edcMagi
      f2_10[0]: /edcHalfMagi
      f2_11[0]: /edcAdjustedCreditAmount
      f2_12[0]: /edcNetCreditAmount
      f2_13[0]: /netEdcAmount
      f2_14[0]: /edcTaxLiabilityLimit
      f2_15[0]: /totalEdc
