server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://state-api-db:5432/stateapi
  liquibase:
    url: jdbc:postgresql://state-api-db:5432/stateapi
    contexts: docker

aws:
  s3:
    accessKey: accessKey
    secretKey: secretKey
    region: us-west-2
    endPoint: http://s3.localhost.localstack.cloud:4566

direct-file:
  backend-url: http://api:${DF_API_PORT:8080}/
