spring:
  liquibase:
    contexts: dev

authorization-token:
  signing-key: GTc+SlI7C7ECPHAhAvIWqn2yAvzAGMVj

aws:
  enabled: false
  s3:
    accessKey: accessKey
    secretKey: secretKey
    region: us-west-2
    certBucketName: cert-bucket
    endPoint: http://s3.localhost.localstack.cloud:4566/

direct-file:
  local-encryption:
    local-wrapping-key: ${LOCAL_WRAPPING_KEY}
  cert-location-override: fakestate.cer
