# set debug: true to log CONDITIONS EVALUATION REPORT
debug: false
logging:
    config: classpath:logback-debug.xml
    file:
        name: spring-boot-debug.log
        clean-history-on-start: true
management:
    endpoints:
        enabled-by-default: true
        web:
            discovery:
                enabled: true
            exposure:
                include: "*"
    endpoint:
        env:
            show-values: ALWAYS
        configprops:
            show-values: ALWAYS
