server:
  port: ${STATEAPI_PORT:8081}
  shutdown: graceful

logging:
  config: classpath:logback.xml

spring:
  datasource:
    username: postgres
    password: postgres
  r2dbc:
    url: r2dbc:postgresql://localhost:${STATEAPI_DB_PORT:5433}/stateapi
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  liquibase:
    change-log: classpath:db/changelog.yaml
    url: jdbc:postgresql://localhost:${STATEAPI_DB_PORT:5433}/stateapi
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    # "If you do not specify any contexts in the CLI at runtime, every changeset in your changelog runs, even if they
    # have contextFilters attached"
    # Setting contexts in the base application.yaml ensures that contextFilters overridden in other profiles are respected
    contexts: base
  cache:
    TTL-minutes: 120
    type: caffeine # Enable caching with Caffeine, use "none" to disable caching

aws:
  default-credentials-provider-chain-enabled: false
  s3:
    default-credentials-provider-chain-enabled: false
    accessKey: accessKey
    secretKey: secretKey
    region: us-east-1
    endPoint: http://localhost:4566
    certBucketName: cert-bucket
    taxReturnXmlBucketName: direct-file-taxreturns
    prefix:

authorization-code:
  expires-interval-seconds: 600

# now we are pointing to direct-file-status app to get status and also xml file, and backend to get exported facts
direct-file:
  backend-url: http://localhost:8080/
  backend-context-path: /df/file/api
  backend-api-version: v1
  status:
    mock: false
    url: ${direct-file.backend-url}
  exported-facts:
    enabled: true
    mock: false
    url: ${direct-file.backend-url}
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      discovery:
        enabled: false
      exposure:
        include: health

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    supported-submit-methods: []

feature-flags:
  export-return:
    variants:
      on: true
      off: false
    default-variant: on

openfeature-starter:
  s3-provider:
    environment-prefix:
    bucket: direct-file-taxreturns
    object: "feature-flags.json"
    expiration: 15m

xml-sanitized:
  allowed-headers:
  excluded-tags:
