includeWhen: /pdfNotOver65SRIndicator
form:
  topmostSubform[0]:
    Page1[0]:
      # Pg1Header[0]:
        # f1_01[0]:
        # f1_02[0]:
        # f1_03[0]:
      f1_04[0]: /primaryFiler/firstNameAndInitial
      f1_05[0]: /primaryFiler/lastName
      SuNumero[0]:
        f1_06[0]: /primaryFiler/tin
      f1_07[0]: /pdfSecondaryFiler/firstNameAndInitial
      f1_08[0]: /pdfSecondaryFiler/lastName
      NumeroDeSeguro[0]:
        f1_09[0]: /pdfSpouseTin
      Address[0]:
        f1_10[0]: /address/streetAddress space /address/streetAddressLine2
        # f1_11[0]:
        f1_12[0]: /address/city
        f1_13[0]: /address/stateOrProvence
        f1_14[0]: /address/postalCode
        # f1_15[0]:
        # f1_16[0]:
        # f1_17[0]:
      c1_01[0]: /primaryFiler/potusElection
      c1_02[0]: /pdfSecondaryFiler/potusElection
      Filing_ReadOrder[0]:
        c1_03[0]: /isFilingStatusSingle
        c1_03[1]: /isFilingStatusMFJ
        c1_03[2]: /isFilingStatusMFS
      c1_03[0]: /isFilingStatusHOH
      c1_03[1]: /isFilingStatusQSS
      f1_18[0]: /mfsSpouseOrQSSAndHOHNotDependentChild space space /xmlNraLiteralCd
      # c1_04[0]:
      # f1_19[0]:
      # c1_05[0]: Off
      c1_05[1]: /notDigitalAssets
      c1_06[0]: /primarySomeoneCanClaimForTaxBenefits
      c1_07[0]: /secondarySomeoneCanClaimForTaxBenefits
      # c1_08[0]:
      c1_09[0]: /primaryFiler/age65OrOlder
      c1_10[0]: /primaryFiler/isBlind
      c1_11[0]: /isSpouse65OrOlder
      c1_12[0]: /secondaryFilerIsBlindIndicatorXml
      Dependientes[0]:
        c1_13[0]: /claimingMoreThan4Dependents
      Table_Dependientes[0]:
        BodyRow1[0]:
          f1_20[0]: /claimedDependentsCollection/[0]/fullName
          f1_21[0]: /claimedDependentsCollection/[0]/tin
          f1_22[0]: /claimedDependentsCollection/[0]/relationship
          c1_14[0]: /claimedDependentsCollection/[0]/isClaimedForCTC
          c1_15[0]: /claimedDependentsCollection/[0]/isClaimedForODC
        BodyRow2[0]:
          f1_23[0]: /claimedDependentsCollection/[1]/fullName
          f1_24[0]: /claimedDependentsCollection/[1]/tin
          f1_25[0]: /claimedDependentsCollection/[1]/relationship
          c1_16[0]: /claimedDependentsCollection/[1]/isClaimedForCTC
          c1_17[0]: /claimedDependentsCollection/[1]/isClaimedForODC
        BodyRow3[0]:
          f1_26[0]: /claimedDependentsCollection/[2]/fullName
          f1_27[0]: /claimedDependentsCollection/[2]/tin
          f1_28[0]: /claimedDependentsCollection/[2]/relationship
          c1_18[0]: /claimedDependentsCollection/[2]/isClaimedForCTC
          c1_19[0]: /claimedDependentsCollection/[2]/isClaimedForODC
        BodyRow4[0]:
          f1_29[0]: /claimedDependentsCollection/[3]/fullName
          f1_30[0]: /claimedDependentsCollection/[3]/tin
          f1_31[0]: /claimedDependentsCollection/[3]/relationship
          c1_20[0]: /claimedDependentsCollection/[3]/isClaimedForCTC
          c1_21[0]: /claimedDependentsCollection/[3]/isClaimedForODC
      f1_32[0]: /wages
      f1_33[0]: /unreportedHouseholdWages
      f1_34[0]: /unreportedTipIncome
      f1_35[0]: /medicareWaiverPayments
      f1_36[0]: /taxableDependentCare
      f1_37[0]: /employerProvidedAdoptionBenefits
      f1_38[0]: /wagesFrom8919
      f1_39[0]: /otherEarnedIncome
      f1_40[0]: /combatPayAmount
      f1_41[0]: /employerIncomeSubtotal
      f1_42[0]: /taxExemptInterest
      f1_43[0]: /interestIncome
      f1_44[0]: /qualifiedDividends
      f1_45[0]: /ordinaryDividends
      Lines4a-11_ReadOrder[0]:
        f1_46[0]: /iraDistributions
        f1_47[0]: /taxableIraDistributions
        f1_48[0]: /pensionsAndAnnuities
        f1_49[0]: /taxablePensionsAndAnnuitiesDisplay
        f1_50[0]: ~positiveSocialSecurityBenefitsOrEmpty
        f1_51[0]: /taxableSocialSecurityBenefits
        c1_22[0]: /socialSecurityLumpSum
        c1_23[0]: /capitalGainsScheduleDNotRequired
        f1_52[0]: /capitalGainsOrLosses
        f1_53[0]: /otherIncome
        f1_54[0]: /totalIncome
        f1_55[0]: /adjustmentsToIncome
        f1_56[0]: /agi
      f1_57[0]: /standardOrItemizedDeductions
      f1_58[0]: /qualifiedBusinessIncomeDeduction
      f1_59[0]: /totalDeductions
      f1_60[0]: /taxableIncome
    Page2[0]:
      c2_01[0]: /form8814Included
      c2_02[0]: /form4972Included
      c2_03[0]: /formOtherIncluded
      f2_01[0]: /otherFormName
      f2_02[0]: /tentativeTaxFromTaxableIncome
      f2_03[0]: /totalAdditionalTaxesOwed
      f2_04[0]: /totalTentativeTax
      f2_05[0]: /totalCtcAndOdc
      f2_06[0]: /line8OfSchedule3
      f2_07[0]: /nonRefundableCredits
      f2_08[0]: /taxLessNonRefundableCredits
      f2_09[0]: /line21OfSchedule2
      f2_10[0]: /totalTax
      f2_11[0]: /formW2Withholding
      f2_12[0]: /form1099Withholding
      f2_13[0]: /otherFormWithholding
      f2_14[0]: /totalWithholding
      f2_15[0]: /estimatedAndFromLastYear
      f2_16[0]: /earnedIncomeCredit
      f2_17[0]: /additionalCtc
      # f2_19[0]:
      f2_18[0]: /americanOpportunityCredit
      f2_20[0]: /otherPaymentsAndRefundableCreditsTotal
      f2_21[0]: /totalOtherPaymentsRefundableCredits
      f2_22[0]: /totalPayments
      f2_23[0]: /overpayment
      c2_04[0]: /form8888Attached
      f2_24[0]: /overpayment
      RoutingNo[0]:
        f2_25[0]: ~pdfRoutingNumberOrXs
      c2_05[0]: /refundAccountIsChecking
      c2_05[1]: /refundAccountIsSavings
      AccountNo[0]:
        f2_26[0]: ~pdfAccountNumberOrXs
      f2_27[0]: /appliedToNextYearEstimated
      f2_28[0]: /balanceDue
      c2_06[0]: /wantsThirdPartyDesignee
      c2_06[1]: /wantsThirdPartyDesigneeNo
      Nombre_ReadOrder[0]:
        f2_30[0]: /pdfThirdPartyDesigneeFullName
      Numero_ReadOrder[0]:
        f2_31[0]: /pdfThirdPartyDesigneePhone
      f2_32[0]: /pdfThirdPartyDesigneePin
      f2_33[0]: /primaryFiler/mefOccupation
      f2_34[0]: /primaryFiler/identityPin
      f2_35[0]: /pdfSecondaryFiler/mefOccupation
      f2_36[0]: /pdfSecondaryFiler/identityPin
      f2_37[0]: /phone
      f2_38[0]: /email
      # f2_38[0]:
      # f2_39[0]:
      # f2_40[0]:
      # c2_07[0]: Off
      # f2_41[0]:
      # f2_42[0]:
      # f2_43[0]:
      # f2_44[0]:
otherRequiredFacts:
  - /dueRefund
  - /xmlRefundBankAccount
  - /socialSecurityBenefits
