includeWhen: /wantsCommsFormat
form:
  form1[0]:
    Pagina1[0]:
      f1_1[0]: /primaryFiler/fullName
      f1_2[0]: /primaryFiler/tin
      DireccionActual[0]:
#       f1_3[0]:  Form9000 instructions say to leave the address section empty if submitting with your tax return
#       f1_4[0]:  Form9000 instructions say to leave the address section empty if submitting with your tax return
#       f1_5[0]:  Form9000 instructions say to leave the address section empty if submitting with your tax return
#       f1_6[0]:  Form9000 instructions say to leave the address section empty if submitting with your tax return
#       f1_7[0]:  Form9000 instructions say to leave the address section empty if submitting with your tax return
#       f1_8[0]:  Form9000 instructions say to leave the address section empty if submitting with your tax return
      c1_1[0]: ~pdfForm9000StandardPrintIsSelected
      c1_1[1]: ~pdfForm9000LargePrintIsSelected
      c1_1[2]: ~pdfForm9000BrailleIsSelected
      c1_1[3]: ~pdfForm9000AudioIsSelected
      c1_1[4]: ~pdfForm9000PlainTextFileIsSelected
      c1_1[5]: ~pdfForm9000BrailleReadyFileIsSelected
otherRequiredFacts:
  - /commsFormat
