includeWhen: /form8862ClaimingMoreThan4CtcDependents
table:
  rowsCollectionPath: /form8862CtcDependentsCollection
  itemsToSkip: 4
  rowsPerPage: 20
  columns:
    - factExpression: ../fullName
      fieldName: Nombre del hijoa línea 12Row
    - factExpression: ../residencyTest
      fieldName: Vivió contigo por más de la mitad del año o cumple con alguna de las excepciones línea 14Row
    - factExpression: ../eligibleCtc
      fieldName: ¿Es un hijo calificado para el CTC/RCTC/ACTC? linea 15Row
    - factExpression: ../isClaimedDependent
      fieldName: Es tu dependiente  línea 16Row
    - factExpression: ../citizenOrUsResidentTest
      fieldName: Es un ciudadano nacional o residente de los Estados Unidos línea 17Row
