spring:
  data:
    redis:
      host: redis
  datasource:
    url: jdbc:postgresql://db:5432/directfile

logging:
  config: classpath:logback-local.xml

direct-file:
  state-api:
    base-url: http://state-api:8080/state-api
  status-endpoint:
    status-endpoint-uri: http://mef-status:8080/status
    rejection-codes-endpoint-uri: http://mef-status:8080/status/rejection-codes
  submit-endpoint:
    submit-endpoint-uri: http://mef-submit:${DF_SUBMIT_PORT}/validate
  pii-service:
    enabled: true
    service-account-name: admin1
    user-attributes-url: http://csp-simulator:8080/internal/user_detail
  aws:
    messageQueue:
      endpoint: http://localstack:4566
    sns:
      endpoint: http://localstack:4566
    kmsEndpoint: http://localstack:4566 #data-import needs kmsClient to encrypt/decrypt SQS msg
  s3-notification-event-cache:
    max-items: 50000
    fixedDelayMilliseconds: 10000 # 10 seconds
    batch-size: 50
