logging:
  config: classpath:logback-local.xml

direct-file:
  pii-service:
    enabled: true
    service-account-name: admin1
    user-attributes-url: http://localhost:${DF_CSPSIM_PORT:5000}/internal/user_detail
  state-api:
#    commenting this out so that it's not set by default, but want to keep here for ease of use
#    version: "2"
  status-endpoint:
    # this is a failing request back to this server (override it in another profile for status to work)
    status-endpoint-uri: http://localhost:${DF_STATUS_PORT:8082}/status
    rejection-codes-endpoint-uri: http://localhost:${DF_STATUS_PORT:8082}/status/rejection-codes
  submit-endpoint:
    submit-endpoint-uri: http://localhost:${DF_SUBMIT_PORT:8083}/validate
  dev-data:
    identity-supplier:
      user-map:
        "00000000-0000-0000-0000-000000000000":
          email: "user.0000@example.com"
          tin: "123456788"
        "00000000-0000-0000-0000-000000000001":
          email: "user.0001@example.com"
          tin: "123456789"

  local-encryption:
    local-wrapping-key: ${LOCAL_WRAPPING_KEY}

  s3-notification-event-cache:
    max-items: 50000
    fixedDelayMilliseconds: 10000 # 10 seconds
    batch-size: 50

aws:
  enabled: false

server:
  port: 8080
