includeForEach: /form1099Rs
form:
  isCorrected: /form1099Rs/*/isCorrected
  payer: /form1099Rs/*/payer newLine /form1099Rs/*/writablePayerNameLine2 newLine /form1099Rs/*/payer/address
  payerPhone: /form1099Rs/*/payer/writablePhone
  payerTin: /form1099Rs/*/payer/tin
  recipient: /form1099Rs/*/filer/fullName newLine /form1099Rs/*/address
  recipientTin: /form1099Rs/*/filer/tin
  grossDistribution: /form1099Rs/*/grossDistribution
  taxableAmount: /form1099Rs/*/taxableAmount
  taxableAmountNotDetermined: /form1099Rs/*/taxableAmountNotDetermined
  totalDistribution: /form1099Rs/*/totalDistribution
  capitalGain: /form1099Rs/*/capitalGain
  federalIncomeTaxWithheld: /form1099Rs/*/federalWithholding
  employeeContributions: /form1099Rs/*/employeeOrRothOrInsuranceContributions
  # netUnrealizedAppreciation: leave blank per ticket 9520
  distributionCode: /form1099Rs/*/distributionCode
  iraSepSimple: /form1099Rs/*/iraSepSimple
  otherAmountDollars: /form1099Rs/*/roundedOtherDollar
  otherAmountPercentage: /form1099Rs/*/writableOtherPercentage
  totalDistributionPercentage: /form1099Rs/*/writablePercentageTotalDistribution
  totalEmployeeContributions: /form1099Rs/*/roundedTotalEmployeeContributions
  irrAllocableAmount: /form1099Rs/*/roundedAmountAllocableToIRR
  firstYearDesignatedRoth: /form1099Rs/*/writableFirstYearDesignatedRothContributions
  # fatcaFilingRequirement: leave blank per ticket 9520
  # dateOfPayment: leave blank per ticket 9520
  accountNumber: /form1099Rs/*/accountNumber
  stateTaxWithheld: /form1099Rs/*/stateTaxWithheld
  stateOrPayerStateNumber: /form1099Rs/*/xmlStateCd space /form1099Rs/*/writablePayerStateNumber
  stateDistribution: /form1099Rs/*/stateDistribution
  localTaxWithheld: /form1099Rs/*/localTaxWithheld
  localityName: /form1099Rs/*/writableLocality
  localDistribution: /form1099Rs/*/localDistribution
