includeForEach: /filersRequiredToFileForm8889
form:
  topmostSubform[0]:
    Page1[0]:
      f1_1[0]: /filersRequiredToFileForm8889/*/hsaPdfFilerName
      f1_2[0]: /filersRequiredToFileForm8889/*/tin
      c1_1[0]: /filersRequiredToFileForm8889/*/isCoveredBySelfOnlyHdhpForExport
      c1_1[1]: /filersRequiredToFileForm8889/*/isCoveredByFamilyHdhpForExport
      f1_3[0]: /filersRequiredToFileForm8889/*/hsaNonemployerContributionsTotalForExport
      # Some lines must use `/filers`. `ExportZero` does not work for aliases.
      f1_4[0]: /filers/*/hsaInitialContributionLimit
      # f1_5[0]:
      f1_6[0]: /filers/*/hsaContributionLimitLessMsaContributions
      f1_7[0]: /filers/*/hsaContributionLimitLessAddition
      f1_8[0]: /filersRequiredToFileForm8889/*/additionToHsaContributionLimit
      f1_9[0]: /filersRequiredToFileForm8889/*/hsaTotalContributionLimit
      f1_10[0]: /filers/*/hsaContributionsW2sTotal
      f1_11[0]: /filersRequiredToFileForm8889/*/hsaFundingDistributionsTotal
      f1_12[0]: /filers/*/hsaEmployerContributionsAndFundingDistributionTotalForExport
      f1_13[0]: /filers/*/hsaContributionLimitLessLine11
      f1_14[0]: /filers/*/hsaTotalDeductibleAmount
      f1_15[0]: /filersRequiredToFileForm8889/*/totalHsaDistributions
      f1_16[0]: /filersRequiredToFileForm8889/*/hsaRolloversAndTimelyWithdrawals
      f1_17[0]: /filers/*/hsaCalculatedDistributionAmount
      f1_18[0]: /filersRequiredToFileForm8889/*/hsaQualifiedMedExpenses
      f1_19[0]: /filers/*/hsaCalculatedTaxableHsaDistributionTotal
      c1_2[0]: Off
      # f1_20[0]:
      # f1_21[0]:
      # f1_22[0]:
      # f1_23[0]:
      # f1_24[0]:
