includeWhen: /wantsCustomLanguage
form:
  topmostSubform[0]:
    Page1[0]:
      f1_1[0]: /primaryFiler/fullName
      f1_2[0]: /primaryFiler/tin
      Line1_ReadOrder[0]:
        c1_1[0]: ~englishIsSelectedLep
        Spanish[0]:
          c1_1[0]: ~spanishIsSelectedLep
        Korean[0]:
          c1_1[0]: ~koreanIsSelectedLep
        Vietnamese[0]:
          c1_1[0]: ~vietnameseIsSelectedLep
        Russian[0]:
          c1_1[0]: ~russianIsSelectedLep
        Arabic[0]:
          c1_1[0]: ~arabicIsSelectedLep
        HaitianCreole[0]:
          c1_1[0]: ~haitianIsSelectedLep
        Tagalog[0]:
          c1_1[0]: ~tagalogIsSelectedLep
        Portuguese[0]:
          c1_1[0]: ~portugueseIsSelectedLep
        Polish[0]:
          c1_1[0]: ~polishIsSelectedLep
        Farsi[0]:
          c1_1[0]: ~farsiIsSelectedLep
      French[0]:
        c1_1[0]: ~frenchIsSelectedLep
      Japanese[0]:
        c1_1[0]: ~japaneseIsSelectedLep
      Gujarati[0]:
        c1_1[0]: ~gujaratiIsSelectedLep
      Punjabi[0]:
        c1_1[0]: ~punjabiIsSelectedLep
      Khmer[0]:
        c1_1[0]: ~khmerIsSelectedLep
      Urdu[0]:
        c1_1[0]: ~urduIsSelectedLep
      Bengali[0]:
        c1_1[0]: ~bengaliIsSelectedLep
      Italian[0]:
        c1_1[0]: ~italianIsSelectedLep
      ChineseTraditional[0]:
        c1_1[0]: ~chineseTraditionalIsSelectedLep
      ChineseSimplified[0]:
        c1_1[0]: ~chineseSimplifiedIsSelectedLep
otherRequiredFacts:
  - /languagePreference
