includeWhen: /pdfIncludeScheduleEic
form:
  topmostSubform[0]:
    Page1[0]:
      f1_1[0]: /primaryFiler/fullName space space /pdfSecondaryFiler/fullName
      f1_2[0]: /primaryFiler/tin
      c1_1[0]: /receivingEitcWhileSeparatedCheckbox
      f1_3[0]: /scheduleEicDependents/[0]/fullName
      f1_4[0]: /scheduleEicDependents/[1]/fullName
      f1_5[0]: /scheduleEicDependents/[2]/fullName
      f1_6[0]: /scheduleEicDependents/[0]/tin
      f1_7[0]: /scheduleEicDependents/[1]/tin
      f1_8[0]: /scheduleEicDependents/[2]/tin
      Year1_ReadOrder[0]:
        f1_9[0]: /scheduleEicDependents/[0]/~birthMillennium
        f1_10[0]: /scheduleEicDependents/[0]/~birthCentury
        f1_11[0]: /scheduleEicDependents/[0]/~birthDecade
        f1_12[0]: /scheduleEicDependents/[0]/~birthYearOfDecade
      Year2_ReadOrder[0]:
        f1_13[0]: /scheduleEicDependents/[1]/~birthMillennium
        f1_14[0]: /scheduleEicDependents/[1]/~birthCentury
        f1_15[0]: /scheduleEicDependents/[1]/~birthDecade
        f1_16[0]: /scheduleEicDependents/[1]/~birthYearOfDecade
      f1_17[0]: /scheduleEicDependents/[2]/~birthMillennium
      f1_18[0]: /scheduleEicDependents/[2]/~birthCentury
      f1_19[0]: /scheduleEicDependents/[2]/~birthDecade
      f1_20[0]: /scheduleEicDependents/[2]/~birthYearOfDecade
      Line4a_Child1_ReadOrder[0]:
        Yes_ReadOrder[0]:
          c1_2[0]: /scheduleEicDependents/[0]/scheduleEicLine4aYes
        c1_2[0]: /scheduleEicDependents/[0]/scheduleEicLine4aNo
      Line4a_Child2_ReadOrder[0]:
        Yes_ReadOrder[0]:
          c1_3[0]: /scheduleEicDependents/[1]/scheduleEicLine4aYes
        c1_3[0]: /scheduleEicDependents/[1]/scheduleEicLine4aNo
      Line4a_Child3_Yes_ReadOrder[0]:
        c1_4[0]: /scheduleEicDependents/[2]/scheduleEicLine4aYes
      c1_4[0]: /scheduleEicDependents/[2]/scheduleEicLine4aNo
      Line4b_Child1_ReadOrder[0]:
        Yes_ReadOrder[0]:
          c1_5[0]: /scheduleEicDependents/[0]/scheduleEicLine4bYes
#       c1_5[0]:
      Line4b_Child2_ReadOrder[0]:
        Yes_ReadOrder[0]:
          c1_6[0]: /scheduleEicDependents/[1]/scheduleEicLine4bYes
#       c1_6[0]:
      Line4b_Child3_Yes_ReadOrder[0]:
        c1_7[0]: /scheduleEicDependents/[2]/scheduleEicLine4bYes
#     c1_7[0]:
      f1_21[0]: /scheduleEicDependents/[0]/relationship
      f1_22[0]: /scheduleEicDependents/[1]/relationship
      f1_23[0]: /scheduleEicDependents/[2]/relationship
      Line6_Child1_ReadOrder[0]:
        f1_24[0]: /scheduleEicDependents/[0]/~transformMonthsLived
      Line6_Child2_ReadOrder[0]:
        f1_25[0]: /scheduleEicDependents/[1]/~transformMonthsLived
      f1_26[0]: /scheduleEicDependents/[2]/~transformMonthsLived
otherRequiredFacts:
  - /scheduleEicDependents/[0]/dateOfBirth
  - /scheduleEicDependents/[1]/dateOfBirth
  - /scheduleEicDependents/[2]/dateOfBirth
  - /scheduleEicDependents/[0]/monthsLivedWithTPInUS
  - /scheduleEicDependents/[1]/monthsLivedWithTPInUS
  - /scheduleEicDependents/[2]/monthsLivedWithTPInUS
customMaps:
  transformMonthsLived:
    # Instructions: enter 7 for more than half of year but less than 7 months
    six: 7
    seven: 7
    eight: 8
    nine: 9
    ten: 10
    eleven: 11
    twelve: 12
