includeWhen: /form8862ClaimingMoreThan4OdcDependents
table:
  rowsCollectionPath: /form8862OdcDependentsCollection
  itemsToSkip: 4
  rowsPerPage: 20
  columns:
    - factExpression: ../fullName
      fieldName: Nombre del otro dependiente línea 13Row
    - factExpression: ../isClaimedDependent
      fieldName: Es tu dependiente línea 16Row
    - factExpression: ../citizenOrUsResidentTest
      fieldName: Es un ciudadano nacional o residente de los Estados Unidos línea 17Row
