includeWhen: /pdfNeedDueDiligenceStatement
table:
  rowsCollectionPath: /cdccCareProvidersWithDueDiligenceReasons
  rowsPerPage: 13
  columns:
    - factExpression: /cdccCareProviders/*/displayName
      fieldName: Care providers nameRow
    - factExpression: /cdccCareProviders/*/~dueDiligence
      fieldName: Reasons why taxpayer cant get the care providers identifying numberRow
otherRequiredFacts:
  - /cdccCareProviders/*/dueDiligence
