includeWhen: /cdccShouldIncludeMoreThanThreeCareProviders
table:
  rowsCollectionPath: /cdccCareProviders
  rowsPerPage: 15
  columns:
    - factExpression: ../displayName
      fieldName: 1 a Care providers nameRow
    - factExpression: ../pdfAddress
      fieldName: b AddressRow
    - factExpression: ../pdfTinEinColumn
      fieldName: c Identifying number SSN or EINRow
    - factExpression: ../pdfIsHouseholdEmployee
      fieldName: d Was the care provider your household employee in 2024Row
    - factExpression: ../amountPaidForCare
      fieldName: e Amount paidRow
  oncePerPage:
    - factExpression: /primaryFiler/fullName
      fieldName: Taxpayer's name
    - factExpression: /primaryFiler/tin
      fieldName: Taxpayer's TIN
