spring:
  devtools:
    restart:
      enabled: false
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:${MEF_APPS_DB_PORT:32768}/directfile-submit
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog.yaml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  hikari:
    maximum-pool-size: 50
    max-lifetime: 450000
    minimum-idle: 30
    connection-timeout: 15000

server:
  port: ${DF_SUBMIT_PORT:8083}
  shutdown: graceful

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      discovery:
        enabled: false
      exposure:
        include: health

submit:
  application-id: ${POD_NAME:dfsys-mef-submit-deployment-0}-${DF_AWS_REGION:us-gov-east-1}
  etin: 11111
  asid: 22222222
  efin: 333333
  vendor-control-number: ${VENDOR_CONTROL_NUMBER_KEY:IRSDIRTAXFPRD001} # this is NOT the correct vendor control number just using a previous example
  softwareId: ${MEF_SOFTWARE_ID_KEY:12345678}
  softwareVersionNum: ${MEF_SOFTWARE_VERSION_NUM:2023.0.1}
  prod: false
  runner-disabled-for-testing: false
  store-validation-results: ${DF_STORE_VALIDATION_RESULTS:false}
  should-disable-mef-connectivity: ${DF_DISABLE_MEF_CONNECTIVITY:false}
  submit-action-enabled: true
  keystore:
    keystore-base64: MISSING
    keystore-password: MISSING
    keystore-alias: MISSING
  directories:
    input: src/main/resources/test/run/input/
    to-process: src/main/resources/test/run/toprocess/
    processed: src/main/resources/test/run/processed/
    batched: src/main/resources/test/run/batched/
    to-batch: src/main/resources/test/run/tobatch/
    submitted: src/main/resources/test/run/submitted/
  intervals:
    returns-to-process: 12000
  documentstore:
    region: us-west-2
    accessKey: accessKey
    secretKey: secretKey
    endpoint: http://s3.localhost.localstack.cloud:4566/
    bucket: direct-file-taxreturns
  messagequeue:
    endpoint: http://localhost:4566
    dispatch-queue: dispatch-queue
    dlq-dispatch-queue: dlq-dispatch-queue
    pending-submission-queue: pending-submission-queue
    pending-submission-publish-enabled: false
    submission-confirmation-queue: submission-confirmation-queue
    submission-confirmation-publish-enabled: false
    sqs-message-handling-enabled: true
    region: us-west-2
    credentials:
      accessKey: accessKey
      secretKey: secretKey
  sns:
    endpoint: http://localhost:4566
    submission-confirmation-topic-arn: arn:aws:sns:us-west-2:000000000000:submission-confirmation-topic
    submission-confirmation-publish-enabled: true
    region: us-west-2
    credentials:
      accessKey: accessKey
      secretKey: secretKey
  submissionid:
    variable-chars: ${SUBMIT_ID_VAR_CHARS:xx}
  batching:
    batchSize: ${SUBMIT_APP_BATCH_SIZE:20}
    batchTimeoutMilliseconds: ${SUBMIT_APP_BATCH_TIMEOUT_MILLIS:5000}  # 1000 milliseconds * 5  = 5 seconds
    errorPollingMilliseconds: ${SUBMIT_APP_ERROR_POLLING_MILLIS:60000} # 1000 milliseconds * 60  = 60 seconds
  mef:
    healthCheckMilliseconds: ${SUBMIT_APP_MEF_HEALTHCHECK_MILLIS:30000} # 1000 milliseconds * 60 seconds * 5 minutes -> 5 minutes
aws:
  enabled: false
  default-credentials-provider-chain-enabled: false
  access-key: accessKey
  secret-key: secretKey
  region: us-west-2

direct-file:
  local-encryption:
    local-wrapping-key: lYIIKutUatfMwdEGB8qtUpQc3wMNtT5pfM+zW57qrv4=
