spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Batching insert/update/delete
        # https://docs.jboss.org/hibernate/orm/6.4/userguide/html_single/Hibernate_User_Guide.html#batch
        jdbc:
          batch_size: 30  # Hibernate docs recommend a value between 10 and 50
    hibernate:
      ddl-auto: validate
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:${DF_EMAIL_DB_PORT:5434}/email-db
  liquibase:
    change-log: classpath:db/changelog.yaml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    transport:
      protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  profiles:
    group:
      development:
      - "blackhole"

server:
  shutdown: graceful

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      discovery:
        enabled: false
      exposure:
        include: health

email-service:
  resend-delay-seconds: 900
  environment: test
  templates:
    location: classpath:templates/**
  messageQueue:
    default-credentials-provider-chain-enabled: false
    send-email-queue: send-mail
    dlq-send-email-queue: dlq-send-mail
    endpoint: http://localhost:4566/
    region: us-west-2
    accessKey: accessKey
    secretKey: secretKey
    sqs-message-handling-enabled: true
  sender:
    from: test@test.com

direct-file:
  local-encryption:
    local-wrapping-key: ${LOCAL_WRAPPING_KEY}
aws:
  enabled: false
