logging:
    config: classpath:logback-debug.xml
management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: "*"
    endpoint:
        env:
            show-values: ALWAYS
        configprops:
            show-values: ALWAYS
