includeWhen: /requiresScheduleB
form:
  topmostSubform[0]:
    Page1[0]:
      f1_01[0]: /primaryFiler/fullName space space /pdfSecondaryFiler/fullName
      f1_02[0]: /primaryFiler/tin
      Line1_ReadOrder[0]:
        f1_03[0]: /interestReports/[0]/payer space space /interestReports/[0]/payerNameLine2
      f1_04[0]: /interestReports/[0]/roundedTaxableInterest
      f1_05[0]: /interestReports/[1]/payer space space /interestReports/[1]/payerNameLine2
      f1_06[0]: /interestReports/[1]/roundedTaxableInterest
      f1_07[0]: /interestReports/[2]/payer space space /interestReports/[2]/payerNameLine2
      f1_08[0]: /interestReports/[2]/roundedTaxableInterest
      f1_09[0]: /interestReports/[3]/payer space space /interestReports/[3]/payerNameLine2
      f1_10[0]: /interestReports/[3]/roundedTaxableInterest
      f1_11[0]: /interestReports/[4]/payer space space /interestReports/[4]/payerNameLine2
      f1_12[0]: /interestReports/[4]/roundedTaxableInterest
      f1_13[0]: /interestReports/[5]/payer space space /interestReports/[5]/payerNameLine2
      f1_14[0]: /interestReports/[5]/roundedTaxableInterest
      f1_15[0]: /interestReports/[6]/payer space space /interestReports/[6]/payerNameLine2
      f1_16[0]: /interestReports/[6]/roundedTaxableInterest
      f1_17[0]: /interestReports/[7]/payer space space /interestReports/[7]/payerNameLine2
      f1_18[0]: /interestReports/[7]/roundedTaxableInterest
      f1_19[0]: /interestReports/[8]/payer space space /interestReports/[8]/payerNameLine2
      f1_20[0]: /interestReports/[8]/roundedTaxableInterest
      f1_21[0]: /interestReports/[9]/payer space space /interestReports/[9]/payerNameLine2
      f1_22[0]: /interestReports/[9]/roundedTaxableInterest
      f1_23[0]: /interestReports/[10]/payer space space /interestReports/[10]/payerNameLine2
      f1_24[0]: /interestReports/[10]/roundedTaxableInterest
      f1_25[0]: /interestReports/[11]/payer space space /interestReports/[11]/payerNameLine2
      f1_26[0]: /interestReports/[11]/roundedTaxableInterest
      f1_27[0]: /interestReports/[12]/payer space space /interestReports/[12]/payerNameLine2
      f1_28[0]: /interestReports/[12]/roundedTaxableInterest
      f1_29[0]: /interestReports/[13]/payer space space /interestReports/[13]/payerNameLine2
      f1_30[0]: /interestReports/[13]/roundedTaxableInterest
      f1_31[0]: /interestIncome
      # f1_32[0]:
      f1_33[0]: /interestIncome # temporary solution while the above line (line 3 is not supported)
      ReadOrderControl[0]:
        # f1_34[0]:
      # f1_35[0]:
      # f1_36[0]:
      # f1_37[0]:
      # f1_38[0]:
      # f1_39[0]:
      # f1_40[0]:
      # f1_41[0]:
      # f1_42[0]:
      # f1_43[0]:
      # f1_44[0]:
      # f1_45[0]:
      # f1_46[0]:
      # f1_47[0]:
      # f1_48[0]:
      # f1_49[0]:
      # f1_50[0]:
      # f1_51[0]:
      # f1_52[0]:
      # f1_53[0]:
      # f1_54[0]:
      # f1_55[0]:
      # f1_56[0]:
      # f1_57[0]:
      # f1_58[0]:
      # f1_59[0]:
      # f1_60[0]:
      # f1_61[0]:
      # f1_62[0]:
      # f1_63[0]:
      # f1_64[0]:
      TagcorrectingSubform[0]:
        c1_1[0]: /hasForeignAccounts
        c1_1[1]: /doesNotHaveForeignAccounts
      # c1_2[0]: Off
      # c1_2[1]: Off
      # f1_65[0]:
      # f1_66[0]:
      # c1_3[0]: Off
      c1_3[0]: /isForeignTrustsGrantorOrHasForeignTrustsTransactions
      c1_3[1]: /isNotForeignTrustsGrantorAndDoesNotHaveForeignTrustsTransactions
