includeWhen: /form8862ClaimingMoreThan4CtcDependents
table:
  rowsCollectionPath: /form8862CtcDependentsCollection
  itemsToSkip: 4
  rowsPerPage: 20
  columns:
    - factExpression: ../fullName
      fieldName: Child name line 12Row
    - factExpression: ../residencyTest
      fieldName: Child lived with you for more than half the year or met an exception line 14Row
    - factExpression: ../eligibleCtc
      fieldName: Is a qualifying child for the CTCRCTCA CTC line 15Row
    - factExpression: ../isClaimedDependent
      fieldName: Is your dependent line 16Row
    - factExpression: ../citizenOrUsResidentTest
      fieldName: Is a citizen national or resident of the United States line 17Row
